'use strict';
// =============================================================================
// Puppy Force — BattleScene.js
// Core turn-based tactical battle
// =============================================================================

// State machine states
const BS = {
  IDLE:         'IDLE',
  UNIT_SEL:     'UNIT_SEL',
  UNIT_MOVED:   'UNIT_MOVED',
  TARGET_ATK:   'TARGET_ATK',
  TARGET_HEAL:  'TARGET_HEAL',
  ENEMY_TURN:   'ENEMY_TURN',
  ANIMATING:    'ANIMATING',
  DIALOGUE:     'DIALOGUE',
  VICTORY:      'VICTORY',
  DEFEAT:       'DEFEAT',
};

class BattleScene extends Phaser.Scene {
  constructor() { super({ key: 'BattleScene' }); }

  // --------------------------------------------------------------------------
  preload() {
    // Load all unit SVG sprites as Phaser textures (self-contained data URIs)
    preloadUnitSprites(this);
    // Audio (graceful — files are optional and may not exist yet)
    AudioManager.preloadMusic(this);
    AudioManager.preloadSFX(this);
    // Suppress load errors for missing optional art assets
    this.load.on('loaderror', () => {}); // silently skip missing optional assets
    // Battle background for current chapter (graceful — file may not exist)
    try {
      const bgKey = `bg_ch${this.chapterId}`;
      this.load.image(bgKey, `assets/backgrounds/chapter_${this.chapterId}_v1.png`);
    } catch (e) {
      // silently skip if the file doesn't exist
    }
    // Enemy portrait/sprite PNG overrides (graceful — fall back to SVG if missing)
    // File naming convention: assets/enemies/<lowercase_id>_v1.png
    const ENEMY_PNG_IDS = [
      'SCOUT_CAT',
      'ALLEY_CAT',
      'SIAMESE_ASSASSIN',
      'PERSIAN_SORCERER',
      'TIGER_GENERAL',
      'LYNX_RANGER',
      'SNOW_LEOPARD',
      'RIVER_PANTHER',
      'SAND_CAT_KING',
      'PERSIAN_QUEEN',
      'CAT_EMPEROR',
    ];
    ENEMY_PNG_IDS.forEach(id => {
      const pngKey = `enemy_png_${id}`;
      if (!this.textures.exists(pngKey)) {
        const fileName = id.toLowerCase() + '_v1.png';
        try {
          this.load.image(pngKey, `assets/enemies/${fileName}`);
        } catch (e) {
          // silently skip — SVG fallback will be used
        }
      }
    });
    // Player portrait PNGs — generated by generate_portraits.py using AI Horde
    // File naming: assets/characters/<ID>_portrait.png  (graceful — falls back to SVG dog)
    const PLAYER_PNG_IDS = [
      'PUPPY_KNIGHT', 'CORGI_HEALER', 'LABRADOR_SCOUT', 'BEAGLE_ARCHER',
      'POODLE_MAGE', 'BULLDOG_TANK', 'HUSKY_RIDER', 'TERRIER_THIEF',
      'FOX_SCOUT', 'OTTER_ALLY', 'DOG_PALADIN',
    ];
    PLAYER_PNG_IDS.forEach(id => {
      const pngKey = `player_png_${id}`;
      if (!this.textures.exists(pngKey)) {
        try {
          this.load.image(pngKey, `assets/characters/${id}_portrait.png`);
        } catch (e) {
          // silently skip — SVG dog sprite will be used instead
        }
      }
    });
    // Terrain tile PNGs (graceful — fall back to colored graphics if missing)
    TERRAIN.forEach((td, i) => {
      const key = `terrain_${i}`;
      if (!this.textures.exists(key)) {
        try {
          this.load.image(key, `assets/terrain/${td.name.toLowerCase()}_v1.png`);
        } catch (e) {
          // silently skip — colored rectangle fallback used in _buildMap
        }
      }
    });
    // Inn art-style variants — match InnScene's file naming exactly
    Object.keys(HERO_DEFS || {}).forEach(id => {
      const lc = id.toLowerCase();
      if (!this.textures.exists(`inn_dark_${id}`))
        this.load.image(`inn_dark_${id}`,  `assets/characters/${lc}_sprite_v1.png`);
      if (!this.textures.exists(`inn_chibi_${id}`))
        this.load.image(`inn_chibi_${id}`, `assets/characters/${lc}_chibi_v1.png`);
    });
    Object.keys(ENEMY_DEFS || {}).forEach(id => {
      const lc = id.toLowerCase();
      if (!this.textures.exists(`inn_dark_${id}`))
        this.load.image(`inn_dark_${id}`,  `assets/enemies/${lc}_pl_v1.png`);
      if (!this.textures.exists(`inn_chibi_${id}`))
        this.load.image(`inn_chibi_${id}`, `assets/enemies/${lc}_chibi_v1.png`);
    });
  }

  // --------------------------------------------------------------------------
  init(data) {
    this.chapterId  = data.chapter || 1;
    this.saveData   = data.saveData || SaveManager.newGame();
    this._state     = BS.IDLE;
    this._selected  = null;    // selected Unit
    this._moveTiles = [];      // reachable tiles
    this._atkTiles  = [];      // attackable tiles
    this._healTiles = [];      // heal-range tiles
    this._preMovPos   = null;    // {col,row} before move for undo
    this._pendingSkill= null;    // offensive skill queued before attack target
    this._lastSkillUsed = null;  // skill used in last _executeCombat call
    this._dlgQueue  = [];        // dialogue lines
    this._dlgIndex  = 0;
    this._enemyQueue= [];      // enemies still to act this turn
    this._levelUps  = [];      // collected during battle
    this._newUnits  = [];      // newly recruited
    this._battleEnded = false; // latch: prevents _endBattle from firing twice
    this._battleGen   = (this._battleGen || 0) + 1; // generation counter for setTimeout safety
    this.turnNumber = 1;
    this.playerTurn = true;
  }

  // --------------------------------------------------------------------------
  create() {
    const chapter = CHAPTERS[this.chapterId - 1];

    // Load roster from save, then place units
    this.roster = SaveManager.deserializeRoster(this.saveData.roster);
    this.mapGrid= chapter.mapGrid;
    this.units  = [];

    // ── Build player units ──────────────────────────────────────────────────
    const maxSlots = Math.min(chapter.playerStart.length, 8);
    for (let i = 0; i < maxSlots; i++) {
      const slot = chapter.playerStart[i];
      const saved= this.roster.find(u => u.id === slot.unitId);
      if (!saved) continue;
      saved.col = slot.col;
      saved.row = slot.row;
      this.units.push(saved);
    }

    // ── Track battle participation ───────────────────────────────────────────
    this.units.filter(u => u.team === 'player').forEach(u => u.battlesParticipated++);

    // ── Build enemy units ───────────────────────────────────────────────────
    chapter.enemies.forEach(spawn => {
      const enemy = buildEnemyUnit(spawn, this.units);
      if (enemy) this.units.push(enemy);
    });

    // ── Build recruitable units (neutral, stand still) ─────────────────────
    this._recruitables = [];
    (chapter.recruitable || []).forEach(r => {
      const def  = HERO_DEFS[r.unitId] || ALLY_DEFS[r.unitId];
      if (!def) return;
      const unit = new Unit(def, r.col, r.row);
      unit.team  = 'neutral';
      unit.rescueMsg = r.rescueMsg;
      this.units.push(unit);
      this._recruitables.push(unit);
    });

    // ── Battle stats for win screen ─────────────────────────────────────────
    this._totalDamageDealt = 0;
    this._unitsLost        = 0;

    // ── Dark background behind the tile grid ────────────────────────────────
    this.add.graphics().setDepth(-20)
      .fillStyle(PAL.BG, 1)
      .fillRect(0, 0, GAME_W, GAME_H);

    // ── Build map and sprites ────────────────────────────────────────────────
    this._buildMap();
    this._buildHighlightLayers();
    this._buildUnitSprites();
    this._buildGridOverlay();

    // ── Camera bounds (support large maps) ───────────────────────────────────
    const mapPixelW = this.mapGrid[0].length * TILE + GRID_X * 2;
    const mapPixelH = this.mapGrid.length    * TILE + GRID_Y * 2;
    this.cameras.main.setBounds(0, 0, mapPixelW, mapPixelH);

    // ── Pan state ────────────────────────────────────────────────────────────
    this._panStart = null;   // {x, y, camX, camY} when drag begins
    this._panning  = false;

    // ── Center camera on player units at start ───────────────────────────────
    const players = this.units.filter(u => u.team === 'player' && !u.dead);
    if (players.length > 0) {
      const avgCol = players.reduce((s, u) => s + u.col, 0) / players.length;
      const avgRow = players.reduce((s, u) => s + u.row, 0) / players.length;
      const { x, y } = this._tileCenter(Math.round(avgCol), Math.round(avgRow));
      this.cameras.main.centerOn(x, y);
    }

    // ── Battle music ─────────────────────────────────────────────────────────
    if (this.cache.audio.exists('battle')) {
      AudioManager.playMusic(this, 'battle');
    } else {
      this.load.once('complete', () => AudioManager.playMusic(this, 'battle'));
      this.load.start();
    }

    // ── UIScene overlay (runs parallel) ─────────────────────────────────────
    if (!this.scene.isActive('UIScene')) {
      this.scene.launch('UIScene', { battleScene: this });
    } else {
      this.scene.get('UIScene').reset(this);
    }

    // ── Input ────────────────────────────────────────────────────────────────
    this.input.on('pointerdown', (pointer) => {
      // Record pan start position for drag-to-pan detection
      this._panStart = {
        x: pointer.x, y: pointer.y,
        camX: this.cameras.main.scrollX,
        camY: this.cameras.main.scrollY,
      };
      this._panning = false;
    }, this);
    this.input.on('pointerdown', this._onTap, this);

    // ── Pinch-to-zoom (two-finger) ───────────────────────────────────────────
    this.input.manager.addPointer(1);   // enable 2nd pointer slot
    this._pinchActive = false;
    this._pinchDist0  = 0;
    this._pinchZoom0  = 1;
    this.input.on('pointermove', (pointer) => {
      const down = this.input.manager.pointers.filter(p => p.isDown);
      if (down.length < 2) {
        this._pinchActive = false;
        // Single-finger drag-to-pan
        if (this._panStart) {
          const dx = pointer.x - this._panStart.x;
          const dy = pointer.y - this._panStart.y;
          if (!this._panning && (Math.abs(dx) > 8 || Math.abs(dy) > 8)) {
            this._panning = true;
          }
          if (this._panning) {
            this.cameras.main.setScroll(
              this._panStart.camX - dx,
              this._panStart.camY - dy
            );
          }
        }
        return;
      }
      const dx   = down[0].x - down[1].x;
      const dy   = down[0].y - down[1].y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      if (!this._pinchActive) {
        this._pinchActive = true;
        this._pinchDist0  = dist;
        this._pinchZoom0  = this.cameras.main.zoom;
      } else {
        const z = Phaser.Math.Clamp(this._pinchZoom0 * (dist / this._pinchDist0), 1, 2.5);
        this.cameras.main.setZoom(z);
      }
    });

    // ── Pointer up — clear pan state ─────────────────────────────────────────
    this.input.on('pointerup', () => {
      this._panStart = null;
      this._panning  = false;
    }, this);

    // ── Opening dialogue → boss intro → IDLE ─────────────────────────────────
    const intro    = chapter.intro || [];
    const afterIntro = () => {
      const bossUnit = chapter.bossId
        ? this.units.find(u => u.id === chapter.bossId && !u.dead)
        : this.units.find(u => u.isBoss && !u.dead);
      if (bossUnit) {
        this._showBossIntro(bossUnit, () => this._setState(BS.IDLE));
      } else {
        this._setState(BS.IDLE);
      }
    };
    if (intro.length > 0) {
      this._startDialogue(intro, afterIntro);
    } else {
      afterIntro();
    }
  }

  // ==========================================================================
  // MAP RENDERING
  // ==========================================================================

  _buildMap() {
    this._tileGfx = this.add.graphics().setDepth(-4);
    const g = this._tileGfx;

    for (let row = 0; row < this.mapGrid.length; row++) {
      for (let col = 0; col < this.mapGrid[0].length; col++) {
        const tid = this.mapGrid[row][col];
        const td  = TERRAIN[tid];
        const x   = GRID_X + col * TILE;
        const y   = GRID_Y + row * TILE;

        // Base fill
        g.fillStyle(td.color, 1);
        g.fillRect(x, y, TILE, TILE);

        // GBA-style pixel art detail
        this._drawTerrainDetail(g, tid, x, y);

        // Crisp 1px dark border (right + bottom edges only — avoids double-drawing)
        g.fillStyle(0x000000, 0.18);
        g.fillRect(x + TILE - 1, y, 1, TILE);
        g.fillRect(x, y + TILE - 1, TILE, 1);
      }
    }
  }

  // Draw GBA-style pixel art detail on top of the base tile fill.
  // Each terrain type uses fillRect / fillCircle / fillEllipse only — no lineStyle —
  // so the look is clean, opaque, and consistent with the Fire Emblem GBA aesthetic.
  _drawTerrainDetail(g, tid, x, y) {
    const cx = x + TILE / 2, cy = y + TILE / 2;

    if (tid === T.GRASS) {
      // ── Grass: scattered "ε" marks (dark olive squiggles) ────────────────
      g.fillStyle(0x4a6810, 0.75);
      const _em = (mx, my) => {
        g.fillRect(mx+2, my,   4, 2); // top bar
        g.fillRect(mx,   my+2, 2, 2); // upper-left
        g.fillRect(mx+2, my+4, 4, 2); // mid bar
        g.fillRect(mx,   my+6, 2, 2); // lower-left
        g.fillRect(mx+2, my+8, 4, 2); // bot bar
      };
      _em(x+3,  y+4);
      _em(x+21, y+3);
      _em(x+7,  y+20);
      _em(x+23, y+21);

    } else if (tid === T.FOREST) {
      // ── Forest: pine canopy from above — dark star-shaped crown ──────────
      const tx = cx, ty = cy - 2;
      // Drop shadow
      g.fillStyle(0x0c2208, 0.7);
      g.fillCircle(tx + 2, ty + 3, 13);
      // Base canopy
      g.fillStyle(0x1a5010, 1);
      g.fillCircle(tx, ty, 13);
      // Star-shaped branch spokes (8 directions)
      g.fillStyle(0x245e14, 1);
      for (let a = 0; a < 8; a++) {
        const ang = (a / 8) * Math.PI * 2 - Math.PI / 8;
        g.fillEllipse(tx + Math.cos(ang) * 8, ty + Math.sin(ang) * 8, 9, 6);
      }
      // Inner crown
      g.fillStyle(0x3a7820, 1);
      g.fillCircle(tx, ty, 7);
      // Highlight (upper-left)
      g.fillStyle(0x508a2c, 1);
      g.fillCircle(tx - 2, ty - 3, 4);
      // Trunk stub at bottom
      g.fillStyle(0x5a2c10, 1);
      g.fillRect(cx - 2, cy + 11, 4, 4);

    } else if (tid === T.MOUNTAIN) {
      // ── Mountain: rocky boulders from above ──────────────────────────────
      g.fillStyle(0x4a3828, 0.9);
      g.fillEllipse(cx - 2, cy + 4, 30, 20);
      g.fillStyle(0x686050, 1);
      g.fillEllipse(cx - 4, cy,     26, 18);
      g.fillStyle(0x7a7060, 1);
      g.fillEllipse(cx + 2, cy - 6, 20, 16);
      // Peak highlight
      g.fillStyle(0x9a9088, 0.8);
      g.fillEllipse(cx, cy - 7, 10, 8);
      // Snow cap
      g.fillStyle(0xe8e8f0, 0.7);
      g.fillCircle(cx, cy - 8, 4);

    } else if (tid === T.WATER) {
      // ── Water: horizontal wave bands + sparkles ──────────────────────────
      g.fillStyle(0x1060a0, 0.35);
      g.fillRect(x + 1, y + 5,  TILE - 2, 5);
      g.fillRect(x + 1, y + 15, TILE - 2, 5);
      g.fillRect(x + 1, y + 25, TILE - 2, 5);
      // Wave crests (lighter)
      g.fillStyle(0x58b8e8, 0.55);
      g.fillRect(x + 3,  y + 6,  10, 2);
      g.fillRect(x + 20, y + 6,  12, 2);
      g.fillRect(x + 7,  y + 16, 12, 2);
      g.fillRect(x + 18, y + 16, 10, 2);
      g.fillRect(x + 3,  y + 26, 10, 2);
      g.fillRect(x + 21, y + 26, 11, 2);

    } else if (tid === T.ROAD) {
      // ── Road: worn-path center stripe, minimal (keep it clean) ───────────
      g.fillStyle(0x9a7018, 0.22);
      g.fillRect(cx - 3, y + 2, 6, TILE - 4);

    } else if (tid === T.SAND) {
      // ── Sand: wind-blown ellipse ripples ─────────────────────────────────
      g.fillStyle(0xa88820, 0.38);
      g.fillEllipse(cx - 7, cy - 5, 22, 6);
      g.fillEllipse(cx + 5, cy + 4, 18, 5);
      g.fillEllipse(cx - 4, cy + 1, 20, 5);

    } else if (tid === T.CASTLE) {
      // ── Castle: stone floor — staggered mortar grid ──────────────────────
      g.fillStyle(0x485060, 0.55);
      // Horizontal mortar
      g.fillRect(x, y + 12, TILE, 1);
      g.fillRect(x, y + 24, TILE, 1);
      // Vertical mortar (staggered rows)
      g.fillRect(cx,      y + 1,  1, 11);
      g.fillRect(cx - 9,  y + 13, 1, 11);
      g.fillRect(cx + 9,  y + 13, 1, 11);
      g.fillRect(cx,      y + 25, 1, 10);
      // Tile highlight corners
      g.fillStyle(0x8898b0, 0.2);
      g.fillRect(x + 1,    y + 1,  5, 3);
      g.fillRect(cx + 1,   y + 1,  5, 3);
      g.fillRect(x + 1,    y + 13, 5, 3);
      g.fillRect(cx + 1,   y + 13, 5, 3);
      g.fillRect(x + 1,    y + 25, 5, 3);
      g.fillRect(cx + 1,   y + 25, 5, 3);

    } else if (tid === T.VILLAGE) {
      // ── Village: house from above — roof ridge + walls + door ────────────
      // Outer wall / floor
      g.fillStyle(0xd09060, 0.9);
      g.fillRect(cx - 10, cy - 6, 20, 16);
      // Roof (darker, triangle peak)
      g.fillStyle(0x7a3828, 1);
      g.fillTriangle(cx - 11, cy - 6, cx, cy - 15, cx + 11, cy - 6);
      // Roof highlight
      g.fillStyle(0x9a5040, 0.8);
      g.fillTriangle(cx - 5, cy - 8, cx, cy - 14, cx + 5, cy - 8);
      // Door
      g.fillStyle(0x583818, 0.9);
      g.fillRect(cx - 2, cy + 4, 4, 6);
      // Windows
      g.fillStyle(0x80b0d0, 0.75);
      g.fillRect(cx - 9, cy - 2, 4, 4);
      g.fillRect(cx + 5, cy - 2, 4, 4);

    } else if (tid === T.SNOW) {
      // ── Snow: small cross-shaped snowflakes scattered ─────────────────────
      g.fillStyle(0xd8eef8, 0.72);
      [[-10,-8],[6,-10],[-4,4],[10,2],[-8,10],[4,10],[0,-2],[8,-4]].forEach(([dx,dy]) => {
        g.fillRect(cx + dx - 1, cy + dy - 3, 2, 6);
        g.fillRect(cx + dx - 3, cy + dy - 1, 6, 2);
      });
      // Snow mound
      g.fillStyle(0xe8f4fc, 0.35);
      g.fillEllipse(cx - 6, cy + 4, 16, 8);
      g.fillEllipse(cx + 5, cy - 4, 13, 7);

    } else if (tid === T.BRIDGE) {
      // ── Bridge: water below + horizontal wooden planks ───────────────────
      // Water hint
      g.fillStyle(0x2060a8, 0.45);
      g.fillRect(x, y, TILE, TILE);
      // Planks (5 horizontal strips)
      g.fillStyle(0xa87030, 1);
      for (let i = 0; i < 5; i++) {
        g.fillRect(x + 2, y + 2 + i * 7, TILE - 4, 5);
      }
      // Plank gaps
      g.fillStyle(0x5c3010, 0.9);
      for (let i = 0; i < 4; i++) {
        g.fillRect(x + 2, y + 7 + i * 7, TILE - 4, 1);
      }
      // Side railings
      g.fillStyle(0x784018, 0.95);
      g.fillRect(x,            y, 3, TILE);
      g.fillRect(x + TILE - 3, y, 3, TILE);

    } else if (tid === T.WALL) {
      // ── Wall: GBA-style 3D stone battlement ──────────────────────────────
      // Top face (lighter — viewed from slightly above)
      g.fillStyle(0xb0bcc8, 1);
      g.fillRect(x, y, TILE, 11);
      // Column cap highlights (3 evenly-spaced pillars)
      g.fillStyle(0xc8d4e0, 1);
      g.fillRect(x + 1,  y + 1, 9, 9);
      g.fillRect(x + 14, y + 1, 8, 9);
      g.fillRect(x + 27, y + 1, 8, 9);
      // Column cap shine
      g.fillStyle(0xdce8f0, 0.8);
      g.fillRect(x + 2,  y + 1, 5, 3);
      g.fillRect(x + 15, y + 1, 5, 3);
      g.fillRect(x + 28, y + 1, 5, 3);
      // Front face (medium stone)
      g.fillStyle(0x7078a0, 1);
      g.fillRect(x, y + 11, TILE, 19);
      // Column fronts (slightly recessed / darker)
      g.fillStyle(0x586088, 1);
      g.fillRect(x + 1,  y + 12, 9,  17);
      g.fillRect(x + 14, y + 12, 8,  17);
      g.fillRect(x + 27, y + 12, 8,  17);
      // Mortar lines on front face
      g.fillStyle(0x2c3440, 1);
      g.fillRect(x,      y + 11, TILE, 1);  // top joint
      g.fillRect(x,      y + 22, TILE, 1);  // mid joint
      g.fillRect(x + 10, y + 12, 1,   17);  // vertical joints
      g.fillRect(x + 22, y + 12, 1,   17);
      g.fillRect(x + 5,  y + 22, 1,   8);   // offset verticals
      g.fillRect(x + 17, y + 22, 1,   8);
      g.fillRect(x + 29, y + 22, 1,   8);
      // Bottom shadow
      g.fillStyle(0x1c2430, 1);
      g.fillRect(x, y + 30, TILE, 6);

    } else if (tid === T.OASIS) {
      // ── Oasis: water pool + palm fronds from above ────────────────────────
      g.fillStyle(0x1878b8, 0.65);
      g.fillCircle(cx, cy + 4, 9);
      g.fillStyle(0x38a0d0, 0.45);
      g.fillCircle(cx - 2, cy + 3, 5);
      // Palm fronds (6 radiating leaves)
      g.fillStyle(0x28882c, 1);
      for (let i = 0; i < 6; i++) {
        const a = (i / 6) * Math.PI * 2;
        g.fillEllipse(cx + Math.cos(a) * 9, cy - 4 + Math.sin(a) * 7, 9, 5);
      }
      // Trunk
      g.fillStyle(0x8a4820, 1);
      g.fillCircle(cx, cy - 4, 3);
    }
  }

  _buildHighlightLayers() {
    this._hlMove  = this.add.graphics(); // Blue: movement
    this._hlAtk   = this.add.graphics(); // Red: attack
    this._hlHeal  = this.add.graphics(); // Green: heal
    this._hlSel   = this.add.graphics(); // Yellow: selected unit
    this._hlCursor= this.add.graphics(); // White pulse: cursor
  }

  _buildGridOverlay() {
    const g = this.add.graphics();
    g.lineStyle(1, 0x000000, 0.08);
    const mapCols = this.mapGrid[0].length;
    const mapRows = this.mapGrid.length;
    for (let col = 0; col <= mapCols; col++) {
      g.lineBetween(GRID_X + col*TILE, GRID_Y, GRID_X + col*TILE, GRID_Y + mapRows*TILE);
    }
    for (let row = 0; row <= mapRows; row++) {
      g.lineBetween(GRID_X, GRID_Y + row*TILE, GRID_X + mapCols*TILE, GRID_Y + row*TILE);
    }
  }

  _buildUnitSprites() {
    this._unitLayer = this.add.container(0, 0);
    this.units.forEach(u => this._createUnitSprite(u));
  }

  _createUnitSprite(unit) {
    const sz = unit.tileSize || 1;
    const { x, y } = this._unitCenter(unit);
    const r = TILE / 2 - 3;
    const halfFoot = (sz * TILE) / 2;

    // Resolve sprite key first so scale can adapt to PNG vs SVG dimensions.
    const sprKey = getSpriteKey(unit, this);

    // Scale: 2x2 bosses fill their footprint; PNG chibi/dark sprites fill one tile;
    // SVG sprites (64×64) fit inside the ring circle.
    let sprScale;
    if (sz === 2) {
      sprScale = (TILE * 1.85) / 64;
    } else if (sprKey.startsWith('inn_') && this.textures.exists(sprKey)) {
      const naturalW = (this.textures.getFrame(sprKey) || { realWidth: 64 }).realWidth;
      sprScale = TILE / naturalW;
    } else {
      const spriteSize = (r * 2 + 2); // fill ~94% of ring (ringR diameter - 2)
      sprScale = spriteSize / 64;
    }

    let sprite;
    if (this.textures.exists(sprKey)) {
      sprite = this.add.image(x, y - 1, sprKey).setOrigin(0.5).setScale(sprScale);
    } else {
      sprite = this.add.text(x, y - 2, unit.emoji, { fontSize: sz === 2 ? '40px' : '26px' }).setOrigin(0.5);
    }

    // 1x1 boss units render 60% larger; 2x2 bosses already fill their footprint via sprScale
    if (unit.isBoss && sz === 1 && sprite.setScale) {
      sprite.setScale(sprScale * 1.6);
    }

    // ── HP bar background ───────────────────────────────────────────────────
    const hpBarW = sz * TILE - 6;
    const hpBg = this.add.rectangle(x, y + halfFoot + 3, hpBarW, 4, 0x000000, 0.7);

    // ── HP bar foreground ───────────────────────────────────────────────────
    const hpBar = this.add.rectangle(x - hpBarW / 2, y + halfFoot + 3, hpBarW, 4, PAL.HP_G, 1);
    hpBar.setOrigin(0, 0.5);

    // ── Drop shadow (rendered below everything else) ─────────────────────────
    const shadow = this.add.ellipse(x, y + halfFoot - 2, sz * TILE - 8, 10, 0x000000, 0.45);

    // ── Class-colored ring background ──────────────────────────────────────
    const ringColor = CLASS_RING_COLOR[unit.unitClass] ||
      (unit.team === 'player' ? PAL.PLAYER_GLOW :
       unit.team === 'neutral' ? 0x44ff88 : PAL.ENEMY_GLOW);
    const ringR = sz === 2 ? TILE * sz / 2 - 2 : r + 2;
    const spriteBg = this.add.circle(x, y, ringR, ringColor, 0.18);
    // Bosses get a thicker, brighter inner ring
    spriteBg.setStrokeStyle(unit.isBoss ? 5 : 3, ringColor, unit.isBoss ? 1.0 : 0.85);

    // ── Boss outer glow ring (pulsing) ───────────────────────────────────────
    let bossGlow = null;
    if (unit.isBoss) {
      const glowR = TILE * sz - 4;
      bossGlow = this.add.circle(x, y, glowR, ringColor, 0.0);
      bossGlow.setStrokeStyle(3, ringColor, 0.55);
      this.tweens.add({
        targets: bossGlow,
        strokeAlpha: { from: 0.55, to: 0.0 },
        radius:      { from: glowR, to: glowR + 10 },
        duration: 1200,
        repeat: -1,
        ease: 'Sine.easeOut',
      });
    }

    // ── Class badge icon (below hp bar) ─────────────────────────────────────
    const badgeColor = unit.team === 'player' ? '#88bbff'
                     : unit.team === 'neutral' ? '#88ffaa'
                     : '#ff8888';
    const badgeLabel = CLASS_ICON[unit.unitClass] || unit.unitClass.slice(0, 4).toUpperCase();
    const badge = this.add.text(x, y + halfFoot + 10, badgeLabel, {
      fontSize: '9px',
      color: badgeColor,
      fontFamily: 'Courier New, monospace',
      fontStyle: 'bold',
    }).setOrigin(0.5, 0);

    unit.shadow    = shadow;
    unit.bossGlow  = bossGlow;
    unit.spriteBg  = spriteBg;
    unit.sprite    = sprite;
    unit.hpBarBg   = hpBg;
    unit.hpBar     = hpBar;
    unit.badge     = badge;

    const layerItems = [shadow];
    if (bossGlow) layerItems.push(bossGlow);
    layerItems.push(spriteBg, sprite, hpBg, hpBar, badge);
    this._unitLayer.add(layerItems);
    this._updateHPBar(unit);

    // ── Idle bob animation ─────────────────────────────────────────────────
    // Player units gently float up and down to signal readiness
    if (unit.team === 'player') {
      this._startIdleBob(unit);
    }
  }

  // Gentle idle float for player units (stored so it can be killed on act)
  _startIdleBob(unit) {
    if (!unit.sprite) return;
    const baseY = unit.sprite.y;
    const bobTween = this.tweens.add({
      targets: unit.sprite,
      y: { from: baseY - 2, to: baseY + 2 },
      duration: 900,
      yoyo: true,
      repeat: -1,
      ease: 'Sine.easeInOut',
      delay: Math.random() * 600, // stagger so units don't all bob in sync
    });
    unit._bobTween = bobTween;
  }

  _stopIdleBob(unit) {
    if (unit._bobTween) {
      unit._bobTween.stop();
      unit._bobTween = null;
      // Snap sprite back to its correct y
      if (unit.sprite) {
        const { y } = this._unitCenter(unit);
        unit.sprite.setY(y - 1);
      }
    }
  }

  // Bounce-pop animation when a unit is selected
  _bounceSprite(unit) {
    if (!unit.sprite) return;
    this._stopIdleBob(unit);
    this.tweens.add({
      targets: unit.sprite,
      scaleX: { from: unit.sprite.scaleX * 1.25, to: unit.sprite.scaleX },
      scaleY: { from: unit.sprite.scaleY * 1.25, to: unit.sprite.scaleY },
      duration: 220,
      ease: 'Back.easeOut',
    });
  }

  _updateHPBar(unit) {
    if (!unit.hpBar) return;
    const sz = unit.tileSize || 1;
    const pct = unit.hp / unit.maxHp;
    const maxW = sz * TILE - 6;
    unit.hpBar.width = maxW * pct;
    unit.hpBar.fillColor = pct > 0.5 ? PAL.HP_G : pct > 0.25 ? PAL.HP_Y : PAL.HP_R;
    const { x } = this._unitCenter(unit);
    unit.hpBar.setX(x - maxW / 2);
    unit.hpBarBg.setX(x);
  }

  _updateSpritePos(unit) {
    if (!unit.sprite) return;
    const sz = unit.tileSize || 1;
    const { x, y } = this._unitCenter(unit);
    const halfFoot = (sz * TILE) / 2;
    if (unit.bossGlow) unit.bossGlow.setPosition(x, y);
    if (unit.spriteBg) unit.spriteBg.setPosition(x, y);
    if (unit.shadow) unit.shadow.setPosition(x, y + halfFoot - 2);
    unit.sprite.setPosition(x, y - 1);
    unit.hpBarBg.setPosition(x, y + halfFoot + 3);
    const hpBarW = sz * TILE - 6;
    unit.hpBar.setX(x - hpBarW / 2);
    unit.hpBar.setY(y + halfFoot + 3);
    if (unit.badge) unit.badge.setPosition(x, y + halfFoot + 10);
    this._updateHPBar(unit);
  }

  _destroyUnitSprite(unit) {
    this._stopIdleBob(unit);
    if (unit._spriteMaskCb) this.events.off('update', unit._spriteMaskCb);
    [unit._spriteMask, unit.shadow, unit.bossGlow, unit.spriteBg, unit.sprite, unit.hpBarBg, unit.hpBar, unit.badge].forEach(o => o && o.destroy());
    unit._spriteMask = unit._spriteMaskCb = unit.shadow = unit.bossGlow = unit.spriteBg = unit.sprite = unit.hpBarBg = unit.hpBar = unit.badge = null;
  }

  // ==========================================================================
  // HIGHLIGHT RENDERING
  // ==========================================================================

  _clearHighlights() {
    this._hlMove.clear();
    this._hlAtk.clear();
    this._hlHeal.clear();
    this._hlSel.clear();
  }

  _drawMoveHighlights(tiles) {
    const g = this._hlMove;
    g.clear();
    tiles.forEach(({ col, row }) => {
      const { x, y } = this._tileTL(col, row);
      g.fillStyle(PAL.MOVE_HL, 0.35);
      g.fillRect(x + 2, y + 2, TILE - 4, TILE - 4);
      g.lineStyle(2, 0x88aaff, 0.9);
      g.strokeRect(x + 2, y + 2, TILE - 4, TILE - 4);
    });
  }

  _drawAtkHighlights(tiles) {
    const g = this._hlAtk;
    g.clear();
    tiles.forEach(({ col, row }) => {
      const { x, y } = this._tileTL(col, row);
      g.fillStyle(PAL.ATK_HL, 0.35);
      g.fillRect(x + 2, y + 2, TILE - 4, TILE - 4);
      g.lineStyle(2, 0xff6666, 0.9);
      g.strokeRect(x + 2, y + 2, TILE - 4, TILE - 4);
    });
  }

  _drawHealHighlights(tiles) {
    const g = this._hlHeal;
    g.clear();
    tiles.forEach(({ col, row }) => {
      const { x, y } = this._tileTL(col, row);
      g.fillStyle(PAL.HEAL_HL, 0.30);
      g.fillRect(x + 2, y + 2, TILE - 4, TILE - 4);
      g.lineStyle(1, PAL.HEAL_HL, 0.7);
      g.strokeRect(x + 2, y + 2, TILE - 4, TILE - 4);
    });
  }

  _drawSelHighlight(unit) {
    const g = this._hlSel;
    g.clear();
    if (!unit) return;
    const { x, y } = this._tileTL(unit.col, unit.row);
    g.lineStyle(4, PAL.SEL_HL, 1);
    g.strokeRect(x + 1, y + 1, TILE - 2, TILE - 2);
    // Animated corner marks
    const sz = 8;
    g.lineStyle(4, PAL.GOLD, 1);
    g.lineBetween(x+1, y+1, x+1+sz, y+1);
    g.lineBetween(x+1, y+1, x+1, y+1+sz);
    g.lineBetween(x+TILE-1, y+1, x+TILE-1-sz, y+1);
    g.lineBetween(x+TILE-1, y+1, x+TILE-1, y+1+sz);
    g.lineBetween(x+1, y+TILE-1, x+1+sz, y+TILE-1);
    g.lineBetween(x+1, y+TILE-1, x+1, y+TILE-1-sz);
    g.lineBetween(x+TILE-1, y+TILE-1, x+TILE-1-sz, y+TILE-1);
    g.lineBetween(x+TILE-1, y+TILE-1, x+TILE-1, y+TILE-1-sz);
  }

  // ==========================================================================
  // INPUT HANDLING
  // ==========================================================================

  _onTap(ptr) {
    if (this._pinchActive) return;          // don't select during two-finger pinch
    if (this._panning)     return;          // don't select when finger was dragging
    if (this._state === BS.DIALOGUE)  { this._advanceDialogue(); return; }
    if (this._state === BS.ANIMATING) return;
    if (this._state === BS.ENEMY_TURN)return;
    if (this._state === BS.VICTORY || this._state === BS.DEFEAT) return;

    // Use worldX/worldY so grid coords stay correct when camera is zoomed
    const col = Math.floor((ptr.worldX - GRID_X) / TILE);
    const row = Math.floor((ptr.worldY - GRID_Y) / TILE);
    if (col < 0 || col >= this.mapGrid[0].length || row < 0 || row >= this.mapGrid.length) return;

    // M3: Update terrain info panel on every tile tap
    const _tappedTerrainId = this.mapGrid[row]?.[col];
    if (_tappedTerrainId !== undefined) this._getUI()?.updateTerrainPanel(_tappedTerrainId);

    switch (this._state) {
      case BS.IDLE:       this._handleIdleTap(col, row);     break;
      case BS.UNIT_SEL:   this._handleSelectTap(col, row);   break;
      case BS.UNIT_MOVED: this._handleMovedTap(col, row);    break;
      case BS.TARGET_ATK: this._handleAtkTargetTap(col, row);break;
      case BS.TARGET_HEAL:this._handleHealTargetTap(col, row);break;
    }
  }

  _handleIdleTap(col, row) {
    const unit = this._unitAt(col, row);
    if (!unit || unit.dead) {
      // Tapped empty tile — clear enemy range preview
      this._clearEnemyRange();
      return;
    }
    if (unit.team === 'player') {
      // Clear enemy range when selecting a player unit
      this._clearEnemyRange();
      // Selectable as long as the unit hasn't both moved AND acted
      if (!(unit.hasMoved && unit.hasActed)) {
        this._selectUnit(unit);
      } else {
        this._showUnitInfo(unit);
      }
    } else {
      // M1: Tap enemy — show their attack range preview in red/orange
      this._showEnemyRange(unit);
      // Show enemy stats in the unit info panel
      this._showUnitInfo(unit);
    }
  }

  _handleSelectTap(col, row) {
    const unit = this._unitAt(col, row);

    // Tap on a move tile
    if (this._moveTiles.some(t => t.col === col && t.row === row)) {
      this._moveSelectedUnit(col, row);
      return;
    }

    // Tap on another friendly unit (still has something to do): switch selection
    if (unit && unit.team === 'player' && !unit.dead && !(unit.hasMoved && unit.hasActed)) {
      this._selectUnit(unit);
      return;
    }

    // Deselect
    this._deselect();
  }

  _handleMovedTap(col, row) {
    const unit = this._unitAt(col, row);
    if (!unit || unit !== this._selected) {
      if (this._preMovPos && col === this._preMovPos.col && row === this._preMovPos.row) {
        this._undoMove();  // tap original tile → undo the move
      } else {
        this._deselect();  // tap anywhere else → cancel / deselect
      }
    }
  }

  _handleAtkTargetTap(col, row) {
    if (!this._atkTiles.some(t => t.col === col && t.row === row)) {
      this._getUI()?.hideDamagePreview();
      this._cancelTargeting(); return;
    }
    const target = this._unitAt(col, row);
    if (!target || target.team !== 'enemy') {
      this._getUI()?.hideDamagePreview();
      this._cancelTargeting(); return;
    }

    // m1: Show damage preview briefly before combat resolves
    const terrainDef = TERRAIN[this.mapGrid[target.row]?.[target.col]]?.def || 0;
    this._getUI()?.showDamagePreview(this._selected, target, terrainDef);

    this._executeCombat(this._selected, target, () => {
      const unit = this._selected;
      if (!unit) return;
      unit.hasActed = true;
      this._checkEndCondition();
      // If game ended, do nothing further
      if (this._state === BS.VICTORY || this._state === BS.DEFEAT) return;
      if (!unit.hasMoved && !unit.dead) {
        // Unit attacked before moving — still allow a move this turn
        const tiles = getReachableTiles(unit, this.mapGrid, this.units);
        this._moveTiles = tiles;
        this._clearHighlights();
        this._drawMoveHighlights(tiles);
        this._drawSelHighlight(unit);
        this._setState(BS.UNIT_SEL);
        this._getUI()?.showActionMenu(unit, this);  // shows Wait/Item; Attack disabled
      } else {
        this._deselect();
      }
    });
  }

  _handleHealTargetTap(col, row) {
    if (!this._healTiles.some(t => t.col === col && t.row === row)) {
      this._cancelTargeting(); return;
    }
    const target = this._unitAt(col, row);
    if (!target || target.team !== 'player') { this._cancelTargeting(); return; }

    this._executeHeal(this._selected, target);
    const unit = this._selected;
    unit.hasActed = true;
    this._checkEndCondition();
    if (this._state === BS.VICTORY || this._state === BS.DEFEAT) return;
    if (!unit.hasMoved && !unit.dead) {
      // Healed before moving — still allow a move this turn
      const tiles = getReachableTiles(unit, this.mapGrid, this.units);
      this._moveTiles = tiles;
      this._clearHighlights();
      this._drawMoveHighlights(tiles);
      this._drawSelHighlight(unit);
      this._setState(BS.UNIT_SEL);
      this._getUI()?.showActionMenu(unit, this);
    } else {
      this._deselect();
    }
  }

  // ==========================================================================
  // UNIT SELECTION & MOVEMENT
  // ==========================================================================

  _selectUnit(unit) {
    this._selected = unit;
    this._clearHighlights();

    if (unit.hasMoved) {
      // Unit already moved this turn — go straight to UNIT_MOVED (no move tiles)
      this._moveTiles = [];
      this._drawSelHighlight(unit);
      this._setState(BS.UNIT_MOVED);
    } else {
      // Unit has not moved yet — show movement + attack-range highlights
      const tiles = getReachableTiles(unit, this.mapGrid, this.units);
      this._moveTiles = tiles;
      this._drawMoveHighlights(tiles);
      // Show attack-range preview from current position (red overlay)
      if (!unit.hasActed) {
        this._drawAtkHighlights(getAttackTiles(unit, this.mapGrid, unit.col, unit.row));
      }
      this._drawSelHighlight(unit);
      this._setState(BS.UNIT_SEL);
    }

    this._getUI()?.showUnitInfo(unit);
    this._getUI()?.showActionMenu(unit, this);  // action menu visible immediately
    this._dimActedUnits();
    this._bounceSprite(unit);
  }

  _deselect() {
    this._selected  = null;
    this._moveTiles = [];
    this._atkTiles  = [];
    this._healTiles = [];
    this._clearHighlights();
    this._clearEnemyRange();
    this._setState(BS.IDLE);
    this._getUI()?.hideActionMenu();
    this._getUI()?.clearUnitInfo();
    this._getUI()?.hideDamagePreview();
    this._dimActedUnits();
    // m5: auto-end turn if all players have moved and acted
    this._checkAutoEndTurn();
  }

  // Cancel targeting (Attack/Heal) and return to unit-selection state with action menu
  _cancelTargeting() {
    const unit = this._selected;
    if (!unit) { this._deselect(); return; }
    this._atkTiles    = [];
    this._healTiles   = [];
    this._pendingSkill = null;  // discard any queued skill so it doesn't leak to next attack
    this._clearHighlights();
    this._getUI()?.hideDamagePreview();
    if (unit.hasMoved) {
      // Was in UNIT_MOVED — just restore sel highlight and menu
      this._drawSelHighlight(unit);
      this._setState(BS.UNIT_MOVED);
    } else {
      // Was in UNIT_SEL — restore move + attack range highlights
      const movTiles = getReachableTiles(unit, this.mapGrid, this.units);
      this._moveTiles = movTiles;
      this._drawMoveHighlights(movTiles);
      if (!unit.hasActed) {
        this._drawAtkHighlights(getAttackTiles(unit, this.mapGrid, unit.col, unit.row));
      }
      this._drawSelHighlight(unit);
      this._setState(BS.UNIT_SEL);
    }
    this._getUI()?.showActionMenu(unit, this);
  }

  _moveSelectedUnit(col, row) {
    const unit = this._selected;
    this._preMovPos = { col: unit.col, row: unit.row };
    this._getUI()?.hideActionMenu();  // hide menu while the walk animation plays

    const path = findPath(unit, col, row, this.mapGrid, this.units);
    this._animateMove(unit, path || [{ col, row }], () => {
      unit.col = col;
      unit.row = row;
      unit.hasMoved = true;
      // Snap sprite to exact tile now that the model is updated
      this._updateSpritePos(unit);
      if (unit.team === 'player' && !unit.hasActed) this._startIdleBob(unit);

      // Terrain landing feedback (Shining Force "land effect" display)
      this._showTerrainLanding(unit);

      // Check if recruitable unit is adjacent
      this._checkRecruitment(unit);

      this._clearHighlights();
      this._drawSelHighlight(unit);
      this._setState(BS.UNIT_MOVED);
      this._getUI()?.showActionMenu(unit, this);
    });
  }

  _undoMove() {
    const unit = this._selected;
    if (!unit || !this._preMovPos) return;
    unit.col = this._preMovPos.col;
    unit.row = this._preMovPos.row;
    unit.hasMoved = false;
    this._preMovPos = null;
    this._updateSpritePos(unit);
    this._selectUnit(unit);
  }

  _animateMove(unit, path, onComplete) {
    if (!path || path.length === 0) { onComplete(); return; }
    this._setState(BS.ANIMATING);

    // Stop idle bob while moving
    this._stopIdleBob(unit);

    const r = TILE / 2 - 3;
    const badgeY = (col, row) => this._tileCenter(col, row).y + r + 10;
    let step = 0;

    const stepDur = Math.max(70, 160 - unit.mov * 8);

    const doStep = () => {
      if (step >= path.length) {
        // NOTE: callers are responsible for updating unit.col/unit.row then
        // calling _updateSpritePos() so the sprite snaps to the exact tile.
        onComplete();
        return;
      }
      const isLastStep = (step === path.length - 1);
      const { col, row } = path[step++];
      const { x, y } = this._tileCenter(col, row);
      const hpY  = y + r + 3;
      const bdgY = y + r + 10;

      // Small paw-print trail dot
      if (unit.sprite) {
        const trail = this.add.circle(
          unit.sprite.x, unit.sprite.y + 4,
          3, 0x99bbff, 0.55
        );
        this.tweens.add({ targets: trail, alpha: 0, y: trail.y - 10, duration: 350, onComplete: () => trail.destroy() });
      }

      // Separate tween per display object (different target y values)
      if (unit.bossGlow) this.tweens.add({ targets: unit.bossGlow, x, y,        duration: stepDur, ease: 'Power1' });
      if (unit.spriteBg) this.tweens.add({ targets: unit.spriteBg, x, y,        duration: stepDur, ease: 'Power1' });
      if (unit.sprite)   this.tweens.add({ targets: unit.sprite,   x, y: y - 1, duration: stepDur, ease: 'Power1' });
      if (unit.hpBarBg)  this.tweens.add({ targets: unit.hpBarBg,  x, y: hpY,  duration: stepDur, ease: 'Power1' });
      if (unit.badge)    this.tweens.add({ targets: unit.badge,    x, y: bdgY, duration: stepDur, ease: 'Power1' });
      if (unit.hpBar) {
        this.tweens.add({
          targets: unit.hpBar,
          x: x - (TILE - 10) / 2,
          y: hpY,
          duration: stepDur,
          ease: 'Power1',
          onComplete: () => {
            if (isLastStep && unit.sprite) {
              const sprite = unit.sprite;
              this.tweens.add({
                targets: sprite,
                scaleX: 1.25, scaleY: 0.75,
                duration: 60, yoyo: true, ease: 'Back.easeOut',
              });
            }
            doStep();
          },
        });
      } else {
        if (isLastStep && unit.sprite) {
          const sprite = unit.sprite;
          this.tweens.add({
            targets: sprite,
            scaleX: 1.25, scaleY: 0.75,
            duration: 60, yoyo: true, ease: 'Back.easeOut',
          });
        }
        this.time.delayedCall(stepDur + 5, doStep);
      }
    };
    doStep();
  }

  // --------------------------------------------------------------------------
  // Action menu callbacks (called by UIScene)
  // --------------------------------------------------------------------------

  onActionAttack() {
    const unit = this._selected;
    if (!unit) return;
    const atkTiles = getAttackTiles(unit, this.mapGrid, unit.col, unit.row);
    const hasTarget = atkTiles.some(t => {
      const u = this._unitAt(t.col, t.row);
      return u && u.team === 'enemy';
    });
    if (!hasTarget) {
      this._getUI()?.showMessage('No enemies in range!');
      return;
    }
    this._atkTiles = atkTiles;
    this._clearHighlights();
    this._drawAtkHighlights(atkTiles);
    this._drawSelHighlight(unit);
    this._setState(BS.TARGET_ATK);
    this._getUI()?.hideActionMenu();
  }

  onActionMagic(skillIndexOrName) {
    const unit = this._selected;
    if (!unit || !unit.skills.length) return;

    // If no specific skill was provided, show the skill selector sub-menu instead
    if (skillIndexOrName === undefined || skillIndexOrName === null) {
      this._getUI()?.showSkillMenu(unit, this);
      return;
    }

    // Resolve skill by index (number) or name/key (string)
    let skill;
    if (typeof skillIndexOrName === 'number') {
      skill = unit.skills[skillIndexOrName];
    } else {
      // Find by skill key (e.g. 'fireball') — must exist in the unit's skill list
      skill = unit.skills.find(s => s === skillIndexOrName);
    }
    if (!skill) return;

    const sk = SKILLS[skill];
    if (!sk) return;

    // MP cost check — cancel immediately if the unit can't afford the skill
    const mpCost = sk.mpCost || 0;
    if (mpCost > 0 && unit.mp < mpCost) {
      this._getUI()?.showMessage(`Not enough MP! (need ${mpCost})`);
      return;
    }

    // Instant buff — no targeting needed
    if (sk.type === 'buff') {
      if (skill === 'guard') {
        if (mpCost > 0) unit.useMp(mpCost);
        unit.guardActive = true;
        unit.hasActed = true;
        this._getUI()?.showUnitInfo(unit); // refresh MP bar
        this._getUI()?.showMessage(`${unit.name} raises their guard!`);
        this._getUI()?.hideActionMenu();
        this._setState(BS.IDLE);
        this._clearHighlights();
        this._deselect();
      }
      return;
    }

    if (sk.targetAlly) {
      // AoE heal (healall) — immediately heal all allies in range without target selection
      if (sk.aoe) {
        if (mpCost > 0) unit.useMp(mpCost);

        const healRange = sk.range || 3;
        const alliesInRange = this.units.filter(u => {
          if (u.dead || u === unit || u.team !== unit.team) return false;
          const dist = Math.abs(u.col - unit.col) + Math.abs(u.row - unit.row);
          return dist <= healRange;
        });

        alliesInRange.forEach(target => {
          const healAmt = Math.floor(unit.atk * Math.abs(sk.power));
          target.hp = Math.min(target.maxHp, target.hp + healAmt);
          this._updateHPBar(target);
          this._floatText(target.col, target.row, `+${healAmt}`, 0x00ff88);
          this._healEffect(target.col, target.row);
        });

        if (alliesInRange.length === 0) {
          this._getUI()?.showMessage('No allies in range!');
          // Refund the MP cost since no one was healed
          if (mpCost > 0) unit.recoverMp(mpCost);
          this._getUI()?.showUnitInfo(unit);
          return;
        }

        unit.hasActed = true;
        unit.hasMoved = true;
        this._getUI()?.showUnitInfo(unit); // refresh MP bar
        this._clearHighlights();
        this._deselect();
        this._checkEndCondition();
        return;
      }

      // Single-target heal — use skill's own range rather than unit's weapon range
      const skillRange = sk.range || unit.range;
      const healTiles = getAttackTiles({ ...unit, range: skillRange }, this.mapGrid, unit.col, unit.row);
      this._healTiles = healTiles;
      this._clearHighlights();
      this._drawHealHighlights(healTiles);
      this._drawSelHighlight(unit);
      this._setState(BS.TARGET_HEAL);
      this._getUI()?.hideActionMenu();
    } else {
      // Offensive skill — use the skill's own range (and minRange if set), not unit's weapon range
      this._pendingSkill = skill;
      const skillRange = sk.range || unit.range;
      const skillOverride = { ...unit, range: skillRange };
      if (sk.minRange) skillOverride.minRange = sk.minRange;
      const atkTiles = getAttackTiles(skillOverride, this.mapGrid, unit.col, unit.row);
      const hasTarget = atkTiles.some(t => {
        const u = this._unitAt(t.col, t.row);
        return u && u.team === 'enemy';
      });
      if (!hasTarget) {
        this._getUI()?.showMessage('No enemies in range!');
        this._pendingSkill = null;
        return;
      }
      this._atkTiles = atkTiles;
      this._clearHighlights();
      this._drawAtkHighlights(atkTiles);
      this._drawSelHighlight(unit);
      this._setState(BS.TARGET_ATK);
      this._getUI()?.hideActionMenu();
    }
  }

  onActionItem(itemIndex = 0) {
    const unit = this._selected;
    if (!unit || unit.items.length === 0) {
      this._getUI()?.showMessage('No items!');
      return;
    }
    // Use item at the specified index (default 0)
    const idx    = Math.min(itemIndex, unit.items.length - 1);
    const itemId = unit.items[idx];
    const item   = ITEMS[itemId];
    if (item && item.heal) {
      const healed = unit.heal(item.heal);
      unit.items.splice(idx, 1);
      this._updateHPBar(unit);
      this._floatText(unit.col, unit.row, `+${healed} HP`, PAL.HP_G);
      unit.hasActed = true;
      this._checkEndCondition();
      this._deselect();
    } else if (item && item.promote && unit.canPromote()) {
      unit.items.splice(idx, 1);
      this._runPromotionCeremony(unit, () => {
        unit.hasActed = true;
        this._checkEndCondition();
        this._deselect();
      });
    }
  }

  onActionWait() {
    const unit = this._selected;
    if (!unit) return;
    unit.hasMoved = true;
    unit.hasActed = true;
    this._checkEndCondition();
    this._deselect();
  }

  onEndTurn() {
    if (this._state === BS.ENEMY_TURN || this._state === BS.ANIMATING) return;
    if (this._state === BS.VICTORY   || this._state === BS.DEFEAT)    return;
    // Cancel any pending auto-end timer to prevent double-fire
    if (this._autoEndTimer) { this._autoEndTimer.remove(); this._autoEndTimer = null; }
    this._deselect();
    this._beginEnemyTurn();
  }

  // ==========================================================================
  // COMBAT
  // ==========================================================================

  _executeCombat(attacker, defender, onDone, hitNum = 1, skillName = null, isDouble = false) {
    this._setState(BS.ANIMATING);
    this._clearHighlights();

    // On the first hit, consume _pendingSkill; on subsequent hits, reuse the passed-in skillName
    if (hitNum === 1) {
      skillName = this._pendingSkill;
      this._pendingSkill = null;
      // Deduct MP cost when the skill is actually executed
      if (skillName) {
        const mpCost = (SKILLS[skillName]?.mpCost) || 0;
        if (mpCost > 0) attacker.useMp(mpCost);
        this._getUI()?.showUnitInfo(attacker); // refresh MP bar in panel
      }
    }
    this._lastSkillUsed = skillName;  // keep updated so noCounter / post-effects always know the skill

    // Combat math
    const atkBonus = skillName ? (SKILLS[skillName].power || 1) : 1;
    const totalHits = (hitNum === 1 && skillName) ? (SKILLS[skillName]?.hits || 1) : 1;
    const isMagicSkill = skillName ? (SKILLS[skillName].type === 'magic') : false;

    // Hit/Miss check — AGI-adjusted; magic is more accurate
    const agiDiff = attacker.agi - defender.agi;
    const baseHit  = isMagicSkill ? 95 : 88;
    const hitChance = Phaser.Math.Clamp(baseHit + agiDiff * 2, 55, 100);
    const hitRoll   = Phaser.Math.Between(1, 100);
    const didHit    = hitRoll <= hitChance;

    // Crit check — only on hits; AGI advantage raises crit chance
    const baseCrit  = isMagicSkill ? 4 : 8;
    const critChance = Phaser.Math.Clamp(baseCrit + Math.max(0, agiDiff), 2, 30);
    const critRoll   = Phaser.Math.Between(1, 100);
    const isCrit     = didHit && (critRoll <= critChance);

    const terrainDef = TERRAIN[this.mapGrid[defender.row][defender.col]]?.def || 0;
    const guardBonus = defender.guardActive ? Math.floor(defender.def * 0.5) : 0;
    const rawDmg = Math.max(1, attacker.atk - (defender.def + guardBonus + terrainDef));
    const variance = Phaser.Math.Between(0, Math.floor(attacker.atk * 0.15));
    // Apply Math.max(1) after atkBonus and variance so skills with power < 1 can't produce 0 damage
    let baseDmg = Math.max(1, Math.floor(rawDmg * atkBonus) + variance);
    // C2: Weapon effectiveness multiplier
    const effectiveness = this._weaponEffectiveness(attacker, defender);
    if (effectiveness > 1.0) baseDmg = Math.round(baseDmg * effectiveness);
    const dmg = isCrit ? Math.floor(baseDmg * 1.5) : baseDmg;

    // Attack animation
    this._shakeSprite(attacker.sprite, () => {
      // On a miss, show EVADE text and bail early
      if (!didHit) {
        this._floatText(defender.col, defender.row, 'EVADE!', 0xaaddff, 20);
        // Still check AGI double-attack after a miss
        const afterMiss = () => {
          if (!isDouble && !attacker.dead && !defender.dead &&
              (attacker.agi - defender.agi) >= 7) {
            this.time.delayedCall(200, () => {
              this._executeCombat(attacker, defender, onDone, 1, null, true);
            });
          } else {
            onDone && onDone();
          }
        };
        this.time.delayedCall(500, afterMiss);
        return;
      }

      // Flash defender
      this.tweens.add({
        targets: [defender.spriteBg, defender.sprite],
        alpha: 0.2, duration: 60, yoyo: true, repeat: isCrit ? 4 : 2,
        onComplete: () => {
          const died = defender.takeDamage(dmg);
          this._totalDamageDealt += dmg;
          this._updateHPBar(defender);
          // Play attack SFX based on skill type (magic vs physical)
          const _sk = skillName ? SKILLS[skillName] : null;
          if (_sk && _sk.type === 'magic') {
            AudioManager.play(this, 'magic_cast');
          } else {
            AudioManager.play(this, 'attack_slash');
          }
          const defSprite = defender.sprite;
          if (defSprite && defSprite.setTint) {
            defSprite.setTint(isCrit ? 0xffaa00 : 0xff4444);
            this.time.delayedCall(isCrit ? 250 : 150, () => defSprite.clearTint());
          }
          if (isCrit) {
            this._floatCritBanner(defender.col, defender.row);
            this._floatText(defender.col, defender.row, `-${dmg}`, 0xffd700, 26);
          } else {
            this._floatText(defender.col, defender.row, `-${dmg}`, PAL.HP_R);
          }
          // C2: Show "Effective!" flash for weapon effectiveness bonus
          if (effectiveness > 1.0) {
            this.time.delayedCall(120, () => this._floatText(defender.col, defender.row, 'Effective!', PAL.GOLD, 15));
          }

          // EXP gain
          const expGain = 10 + Math.floor(dmg / 2);
          const leveled = attacker.gainExp(expGain);
          if (leveled) this._onLevelUp(attacker);

          if (died) {
            if (attacker.team === 'player') attacker.killCount++;
            // Kill bonus XP — uses enemy's expReward so 1 kill ≈ 1 level in ch1
            if (attacker.team === 'player' && defender.expReward) {
              if (attacker.gainExp(defender.expReward)) this._onLevelUp(attacker);
            }
            this._killUnit(defender, () => {
              // Counter-attack possible for melee defenders?
              // (no counter if dead)
              onDone && onDone();
            });
            return;
          }

          // Counter-attack: defender can retaliate if attacker is within defender's weapon range
          const dist = Math.abs(attacker.col - defender.col) + Math.abs(attacker.row - defender.row);
          // Wrap onDone to check for AGI double-attack after the full sequence resolves
          const afterSequence = () => {
            if (!isDouble && !attacker.dead && !defender.dead &&
                (attacker.agi - defender.agi) >= 7) {
              this._floatText(attacker.col, attacker.row, '2×', PAL.GOLD);
              this.time.delayedCall(200, () => {
                this._executeCombat(attacker, defender, onDone, 1, null, true);
              });
            } else {
              onDone && onDone();
            }
          };

          const noCounter = this._lastSkillUsed ? (SKILLS[this._lastSkillUsed]?.noCounter || false) : false;
          const canCounter = !noCounter && dist <= defender.range && defender.team === 'enemy';
          if (canCounter) {
            const cDef = TERRAIN[this.mapGrid[attacker.row][attacker.col]]?.def || 0;
            const cRaw = Math.max(1, defender.atk - (attacker.def + cDef));
            const cVar = Phaser.Math.Between(0, Math.floor(defender.atk * 0.1));
            // Counter-attack hit/crit check (enemy counters)
            const cAgiDiff  = defender.agi - attacker.agi;
            const cHitChance = Phaser.Math.Clamp(85 + cAgiDiff * 2, 55, 100);
            const cHit       = Phaser.Math.Between(1, 100) <= cHitChance;
            const cCrit      = cHit && (Phaser.Math.Between(1, 100) <= Phaser.Math.Clamp(6 + Math.max(0, cAgiDiff), 2, 25));
            const cBaseDmg   = cRaw + cVar;
            const cDmg       = cCrit ? Math.floor(cBaseDmg * 1.5) : cBaseDmg;

            this.time.delayedCall(300, () => {
              this._shakeSprite(defender.sprite, () => {
                if (!cHit) {
                  this._floatText(attacker.col, attacker.row, 'EVADE!', 0xaaddff, 20);
                  this.time.delayedCall(400, () => this._applyPostCombatEffects(attacker, defender, afterSequence));
                  return;
                }
                this.tweens.add({
                  targets: [attacker.spriteBg, attacker.sprite],
                  alpha: 0.2, duration: 60, yoyo: true, repeat: cCrit ? 4 : 2,
                  onComplete: () => {
                    const aDied = attacker.takeDamage(cDmg);
                    this._updateHPBar(attacker);
                    if (cCrit) {
                      this._floatCritBanner(attacker.col, attacker.row);
                      this._floatText(attacker.col, attacker.row, `-${cDmg}`, 0xffd700, 26);
                    } else {
                      this._floatText(attacker.col, attacker.row, `-${cDmg}`, 0xff8844);
                    }
                    const expGain2 = Math.floor(cDmg / 3);
                    const leveled2 = defender.gainExp(expGain2);
                    if (leveled2) this._onLevelUp(defender);

                    if (aDied) {
                      if (defender.team === 'player') defender.killCount++;
                      this._killUnit(attacker, onDone);
                    } else {
                      this._applyPostCombatEffects(attacker, defender, afterSequence);
                    }
                  },
                });
              });
            });
          } else {
            if (totalHits > 1 && hitNum < totalHits && !defender.dead) {
              // Fire second hit after short delay
              this.time.delayedCall(200, () => {
                this._executeCombat(attacker, defender, onDone, hitNum + 1, skillName, isDouble);
              });
            } else {
              this._applyPostCombatEffects(attacker, defender, afterSequence);
            }
          }
        },
      });
    });
  }

  _applyPostCombatEffects(attacker, defender, onDone) {
    const sk = this._lastSkillUsed ? SKILLS[this._lastSkillUsed] : null;
    if (!sk) { onDone && onDone(); return; }

    // KNOCKBACK (charge)
    if (sk.knockback && !defender.dead) {
      const dx = defender.col - attacker.col;
      const dy = defender.row - attacker.row;
      const len = Math.max(Math.abs(dx), Math.abs(dy)) || 1;
      const nx = defender.col + Math.sign(dx / len);
      const ny = defender.row + Math.sign(dy / len);
      if (nx >= 0 && nx < this.mapGrid[0].length && ny >= 0 && ny < this.mapGrid.length &&
          (TERRAIN[this.mapGrid[ny][nx]]?.movCost ?? 99) < 99 &&
          !this._unitAt(nx, ny)) {
        defender.col = nx;
        defender.row = ny;
        this._updateSpritePos(defender);
        this._floatText(nx, ny, '↗ Pushed!', 0xffaa44);
      }
    }

    // DIVE REPOSITION (dash) — move attacker adjacent to defender
    if (sk.dive && !defender.dead) {
      const dx = defender.col - attacker.col;
      const dy = defender.row - attacker.row;
      let nx, ny;
      if (Math.abs(dx) >= Math.abs(dy)) {
        nx = attacker.col + Math.sign(dx);
        ny = attacker.row;
      } else {
        nx = attacker.col;
        ny = attacker.row + Math.sign(dy);
      }
      if (nx >= 0 && nx < this.mapGrid[0].length && ny >= 0 && ny < this.mapGrid.length && !this._unitAt(nx, ny)) {
        attacker.col = nx;
        attacker.row = ny;
        this._updateSpritePos(attacker);
      }
    }

    // SPLASH (fireball) — hit all enemies adjacent to defender
    if (sk.splash && !defender.dead) {
      const splashPower = sk.splash;
      const adjEnemies = this.units.filter(u =>
        !u.dead && u.team === 'enemy' && u !== defender &&
        Math.abs(u.col - defender.col) + Math.abs(u.row - defender.row) === 1
      );
      adjEnemies.forEach(u => {
        const tDef = TERRAIN[this.mapGrid[u.row][u.col]]?.def || 0;
        const sRaw = Math.max(1, attacker.atk - (u.def + tDef));
        const sDmg = Math.max(1, Math.floor(sRaw * splashPower));
        const died = u.takeDamage(sDmg);
        this._updateHPBar(u);
        this._floatText(u.col, u.row, `-${sDmg} Fire`, 0xff6600);
        if (died) this._killUnit(u, () => {});
      });
    }

    // BURN DoT (fireball)
    if (sk.burn && !defender.dead) {
      defender.burnStacks = (defender.burnStacks || 0) + sk.burn;
      this._floatText(defender.col, defender.row, 'Burn!', 0xff4400);
    }

    onDone && onDone();
  }

  _executeHeal(healer, target) {
    const sk = SKILLS['heal'];
    // Use skill power magnitude to scale heal (power is negative to denote healing)
    const skillPower = sk ? Math.abs(sk.power) : 1.0;
    const healAmt = Math.floor(healer.atk * skillPower) + Phaser.Math.Between(2, 6);
    const actual  = target.heal(healAmt);
    this._updateHPBar(target);
    AudioManager.play(this, 'heal');
    const targetSprite = target.sprite;
    if (targetSprite && targetSprite.setTint) {
      targetSprite.setTint(0x44ff88);
      this.time.delayedCall(200, () => targetSprite.clearTint());
    }
    this._floatText(target.col, target.row, `+${actual} HP`, PAL.HP_G);

    const expGain = 25; // 4 heals ≈ 1 level; keeps pace with combat units
    const leveled = healer.gainExp(expGain);
    if (leveled) this._onLevelUp(healer);

    // Spark effect on target
    this._healEffect(target.col, target.row);
  }

  _killUnit(unit, onDone) {
    AudioManager.play(this, 'unit_death');
    const deathTargets = [unit.bossGlow, unit.spriteBg, unit.sprite, unit.hpBar, unit.hpBarBg].filter(Boolean);
    // Kill any pre-existing tweens on these targets (e.g. boss glow repeat:-1)
    // to prevent them from interfering with the death tween's onComplete.
    deathTargets.forEach(t => this.tweens.killTweensOf(t));
    this.tweens.add({
      targets: deathTargets,
      alpha: 0, scaleX: 1.5, scaleY: 1.5, duration: 400,
      ease: 'Power2',
      onComplete: () => {
        this._destroyUnitSprite(unit);
        unit.dead = true;
        if (unit.team === 'player') this._unitsLost++;
        this._checkEndCondition();
        onDone && onDone();
      },
    });
  }

  // ==========================================================================
  // ENEMY AI TURN
  // ==========================================================================

  _beginEnemyTurn() {
    this.playerTurn = false;
    this.turnNumber++;
    this._setState(BS.ENEMY_TURN);
    this._getUI()?.showTurnBanner('Enemy Turn', 0xff4444);

    // Apply burn DoT to all burning units
    this.units.filter(u => !u.dead && u.burnStacks > 0).forEach(u => {
      const bDmg = u.burnStacks;
      u.burnStacks--;
      const died = u.takeDamage(bDmg);
      this._updateHPBar(u);
      AudioManager.play(this, 'burn_crackle');
      this._floatText(u.col, u.row, `-${bDmg} Fire`, 0xff4400);
      if (died) this._killUnit(u, () => {});
    });

    // M2: Sort by AGI descending so faster enemies act first
    this._enemyQueue = this.units.filter(u => !u.dead && u.team === 'enemy')
      .sort((a, b) => b.agi - a.agi);
    // Enemy units need their turn state reset so they can act this turn
    this._enemyQueue.forEach(u => u.resetTurn());

    this.time.delayedCall(800, () => this._processNextEnemy());
  }

  _processNextEnemy() {
    if (this._state === BS.VICTORY || this._state === BS.DEFEAT) return;
    // Remove dead from queue
    this._enemyQueue = this._enemyQueue.filter(u => !u.dead);

    if (this._enemyQueue.length === 0) {
      this._beginPlayerTurn();
      return;
    }

    const enemy = this._enemyQueue.shift();
    const action = computeEnemyAction(enemy, this.mapGrid, this.units);

    // Move
    // action.moveTo is already validated by getReachableTiles; follow the full path
    const path = findPath(enemy, action.moveTo.col, action.moveTo.row, this.mapGrid, this.units);

    this._animateMove(enemy, path && path.length > 0 ? path : [action.moveTo], () => {
      enemy.col = action.moveTo.col;
      enemy.row = action.moveTo.row;
      enemy.hasMoved = true;
      // Snap sprite to exact tile now that the model is updated
      this._updateSpritePos(enemy);

      if (action.target && !action.target.dead) {
        this._executeCombat(enemy, action.target, () => {
          if (this._state === BS.VICTORY || this._state === BS.DEFEAT) return;
          enemy.hasActed = true;
          this.time.delayedCall(200, () => this._processNextEnemy());
        });
      } else {
        enemy.hasActed = true;
        this.time.delayedCall(150, () => this._processNextEnemy());
      }
    });
  }

  _beginPlayerTurn() {
    this.playerTurn = true;
    this.units.filter(u => !u.dead && u.team === 'player').forEach(u => u.resetTurn());

    // C3: Clear guard buffs at the START of the player's next turn (was incorrectly in _beginEnemyTurn)
    this.units.filter(u => u.team === 'player').forEach(u => { u.guardActive = false; });

    // m6: MP recovery — each player unit recovers 10% of max MP at the start of their turn (was 20%)
    this.units.filter(u => !u.dead && u.team === 'player').forEach(u => { u.recoverMp(Math.max(1, Math.round(u.maxMp * 0.10))); });

    // m10: Village tile healing — player units on VILLAGE tiles (tid=7) heal 3 HP
    const chapter = CHAPTERS[this.chapterId - 1];
    this.units.filter(u => !u.dead && u.team === 'player').forEach(unit => {
      const tid = chapter.mapGrid[unit.row]?.[unit.col];
      if (tid === 7 /* VILLAGE */ && unit.hp < unit.maxHp) {
        unit.hp = Math.min(unit.maxHp, unit.hp + 3);
        this._updateHPBar(unit);
        this._healEffect(unit.col, unit.row);
        this._floatText(unit.col, unit.row, '+3 HP', PAL.HP_G);
      }
    });

    // Refresh UI panel if a unit is currently selected
    if (this._selected) this._getUI()?.showUnitInfo(this._selected);

    this._setState(BS.IDLE);
    this._dimActedUnits();
    this._getUI()?.showTurnBanner('Your Turn', 0xf8c030);
  }

  // ==========================================================================
  // RECRUITMENT (adjacent player to recruitable)
  // ==========================================================================

  _checkRecruitment(movedUnit) {
    if (movedUnit.team !== 'player') return;
    this._recruitables.forEach(r => {
      if (r.team !== 'neutral' || r.dead) return;
      const minDist = Math.min(
        ...movedUnit.getTilesOccupied().flatMap(mt =>
          r.getTilesOccupied().map(rt =>
            Math.abs(mt.col - rt.col) + Math.abs(mt.row - rt.row)
          )
        )
      );
      if (minDist === 1) {
        // Recruit!
        r.team = 'player';
        this._recruitables.splice(this._recruitables.indexOf(r), 1);
        this._newUnits.push({ name: r.name, emoji: r.emoji });
        // Update sprite color
        if (r.spriteBg) {
          r.spriteBg.setFillStyle(0x224488, 0.95);
          r.spriteBg.setStrokeStyle(2, PAL.PLAYER_GLOW, 0.9);
        }
        // Add to roster
        this.saveData.roster.push(r.toSave());
        this._floatText(r.col, r.row, r.rescueMsg || 'Joins!', 0x44ff88);
        this._getUI()?.showMessage(r.rescueMsg || `${r.name} joined!`);
      }
    });
  }

  // ==========================================================================
  // WIN / LOSE CHECK
  // ==========================================================================

  _checkEndCondition() {
    if (this._state === BS.VICTORY || this._state === BS.DEFEAT) return;

    const chapter = CHAPTERS[this.chapterId - 1];
    const players = this.units.filter(u => !u.dead && u.team === 'player');
    const enemies = this.units.filter(u => !u.dead && u.team === 'enemy');

    // Defeat: all player units dead
    if (players.length === 0) {
      this._setState(BS.DEFEAT);
      this._getUI()?.showMessage('All units defeated!');
      this.time.delayedCall(1500, () => this._endBattle(false));
      const gen = this._battleGen;
      setTimeout(() => { if (this._battleGen === gen) this._endBattle(false); }, 2000); // safety net
      return;
    }

    // Victory: chapter's designated boss is dead (prefer bossId, fall back to any isBoss)
    const boss = chapter.bossId
      ? this.units.find(u => u.id === chapter.bossId)
      : this.units.find(u => u.isBoss);
    if (boss && boss.dead) {
      this._setState(BS.VICTORY);
      this._celebrateVictory();
      return;
    }

    // Victory fallback: all enemies dead
    if (enemies.length === 0) {
      this._setState(BS.VICTORY);
      this._celebrateVictory();
      return;
    }
  }

  _celebrateVictory() {
    // Show a victory message and immediately end the battle —
    // no in-battle dialogue loop so the screen never gets stuck.
    this._getUI()?.showMessage('Victory! 🏆');
    this.time.delayedCall(1500, () => this._endBattle(true));
    // Safety net: if the Phaser timer fails to fire (e.g. scene clock
    // hiccup), use a raw setTimeout as a fallback so the game never
    // gets permanently stuck on the victory banner.
    const gen = this._battleGen;
    setTimeout(() => { if (this._battleGen === gen) this._endBattle(true); }, 2000);
  }

  _endBattle(victory) {
    if (this._battleEnded) return;
    this._battleEnded = true;
    // Save progress
    if (victory) {
      const completed = this.saveData.completedChapters || [];
      if (!completed.includes(this.chapterId)) completed.push(this.chapterId);
      this.saveData.completedChapters = completed;
      this.saveData.currentChapter = Math.min(7, this.chapterId + 1);
      // Update roster with current unit states
      // M7: Dead units revive at 1 HP with NO training bonus — only living units get +2 HP, +1 ATK
      const survivors = this.units.filter(u => u.team === 'player');
      survivors.forEach(u => {
        if (u.dead) {
          // Revive with 1 HP, no training bonus (death has consequences)
          u.dead = false;
          u.hp = 1;
        } else {
          // Living survivors get the inter-chapter training bonus
          u.maxHp += 2;
          u.hp = u.maxHp;
          u.atk += 1;
        }
      });
      this.saveData.roster = SaveManager.serializeRoster(survivors);
      SaveManager.save(this.saveData);
    }

    this.scene.stop('UIScene');
    const chapter = CHAPTERS[this.chapterId - 1];
    this.scene.start('VictoryScene', {
      result:        victory ? 'victory' : 'defeat',
      chapter:       this.chapterId,
      saveData:      this.saveData,
      levelUps:      this._levelUps,
      newUnits:      this._newUnits,
      victoryLines:  victory ? (chapter.victory || []) : [],
      totalDamage:   this._totalDamageDealt,
      unitsLost:     this._unitsLost,
      turns:         this.turnNumber,
    });
  }

  // ==========================================================================
  // PROMOTION CEREMONY
  // ==========================================================================

  _runPromotionCeremony(unit, onDone) {
    this._setState(BS.ANIMATING);
    const W = GAME_W, H = GAME_H;
    const { x: ux, y: uy } = this._tileCenter(unit.col, unit.row);

    // Snapshot stats BEFORE promotion for comparison card
    const beforeName = unit.name;
    const beforeEmoji = unit.emoji;
    const beforeStats = { hp: unit.maxHp, atk: unit.atk, def: unit.def, mov: unit.mov, agi: unit.agi };

    // ── Phase 1: bright white flash + rising gold light rays ──────────────
    const overlay = this.add.rectangle(W/2, H/2, W, H, 0xffffff, 0).setDepth(50);
    this.tweens.add({ targets: overlay, alpha: 0.85, duration: 300, yoyo: true, onComplete: () => overlay.destroy() });
    this.cameras.main.shake(120, 0.012);

    // Gold light-ray particles bursting from unit
    for (let i = 0; i < 16; i++) {
      const angle = (i / 16) * Math.PI * 2;
      const ray = this.add.rectangle(ux, uy, 3, Phaser.Math.Between(20, 60), 0xffd700, 0.9)
        .setRotation(angle).setDepth(48);
      this.tweens.add({
        targets: ray,
        x: ux + Math.cos(angle) * 80,
        y: uy + Math.sin(angle) * 80,
        alpha: 0,
        scaleY: 0.2,
        duration: 700,
        delay: i * 20,
        ease: 'Power2',
        onComplete: () => ray.destroy(),
      });
    }

    // Sparkle dots
    for (let i = 0; i < 20; i++) {
      const dot = this.add.circle(
        ux + Phaser.Math.Between(-50, 50),
        uy + Phaser.Math.Between(-50, 50),
        Phaser.Math.Between(3, 7), 0xffd700, 1
      ).setDepth(49);
      this.tweens.add({
        targets: dot, alpha: 0, y: dot.y - Phaser.Math.Between(30, 70),
        duration: 800, delay: i * 30,
        onComplete: () => dot.destroy(),
      });
    }

    // ── Phase 2: apply promotion & swap sprite ─────────────────────────────
    this.time.delayedCall(400, () => {
      unit.promote();
      if (unit.sprite && unit.sprite.setTexture) {
        unit.sprite.setTexture(getSpriteKey(unit, this));
      }
      AudioManager.play(this, 'level_up');

      // Promoted class name banner
      this._floatText(unit.col, unit.row, `${unit.emoji} ${unit.name}!`, 0xffd700, 20);

      // ── Phase 3: stat comparison card after 700ms ──────────────────────
      this.time.delayedCall(700, () => {
        this._showPromotionCard(unit, beforeName, beforeEmoji, beforeStats, () => {
          this._setState(BS.UNIT_MOVED);
          onDone && onDone();
        });
      });
    });
  }

  _showPromotionCard(unit, beforeName, beforeEmoji, beforeStats, onDone) {
    const W = GAME_W, H = GAME_H;
    const cardW = 300, cardH = 220, cardX = (W - cardW) / 2, cardY = (H - cardH) / 2 - 20;

    // Semi-transparent dark backdrop
    const backdrop = this.add.rectangle(W/2, H/2, W, H, 0x000000, 0.65).setDepth(55).setInteractive();

    const cardBg = this.add.graphics().setDepth(56);
    cardBg.fillStyle(0x0a1a2e, 0.98);
    cardBg.fillRoundedRect(cardX, cardY, cardW, cardH, 12);
    cardBg.lineStyle(2, 0xffd700, 0.9);
    cardBg.strokeRoundedRect(cardX, cardY, cardW, cardH, 12);

    const cx = cardX + cardW / 2;
    // Header
    this.add.text(cx, cardY + 18, '★  PROMOTION!  ★', {
      fontSize: '18px', color: '#ffd700', fontStyle: 'bold',
      fontFamily: 'Nunito, Courier New, monospace',
      stroke: '#000', strokeThickness: 3,
    }).setOrigin(0.5).setDepth(57);

    // Before → After names
    this.add.text(cx, cardY + 46, `${beforeEmoji} ${beforeName}  →  ${unit.emoji} ${unit.name}`, {
      fontSize: '13px', color: '#aaddff', fontStyle: 'bold',
      fontFamily: 'Nunito, Courier New, monospace',
      stroke: '#000', strokeThickness: 2,
    }).setOrigin(0.5).setDepth(57);

    // Stat diff rows
    const stats = [
      { label: 'HP',  before: beforeStats.hp,  after: unit.maxHp },
      { label: 'ATK', before: beforeStats.atk, after: unit.atk  },
      { label: 'DEF', before: beforeStats.def, after: unit.def  },
      { label: 'MOV', before: beforeStats.mov, after: unit.mov  },
      { label: 'AGI', before: beforeStats.agi, after: unit.agi  },
    ];
    let sy = cardY + 72;
    stats.forEach(s => {
      const diff = s.after - s.before;
      const diffStr = diff > 0 ? `+${diff}` : `${diff}`;
      const diffCol = diff > 0 ? '#44ff88' : (diff < 0 ? '#ff4444' : '#888888');
      this.add.text(cardX + 28, sy, `${s.label}:  ${s.before}  →  ${s.after}`, {
        fontSize: '14px', color: '#ccddff', fontStyle: 'bold',
        fontFamily: 'Nunito, Courier New, monospace',
        stroke: '#000', strokeThickness: 2,
      }).setDepth(57);
      this.add.text(cardX + cardW - 28, sy, diffStr, {
        fontSize: '14px', color: diffCol, fontStyle: 'bold',
        fontFamily: 'Nunito, Courier New, monospace',
        stroke: '#000', strokeThickness: 2,
      }).setOrigin(1, 0).setDepth(57);
      sy += 22;
    });

    // Tap to continue hint
    const hint = this.add.text(cx, cardY + cardH - 18, '▶ TAP TO CONTINUE', {
      fontSize: '12px', color: '#aabbcc', fontStyle: 'bold',
      fontFamily: 'Nunito, Courier New, monospace',
    }).setOrigin(0.5).setDepth(57);
    this.tweens.add({ targets: hint, alpha: { from: 0.3, to: 1 }, duration: 600, yoyo: true, repeat: -1 });

    // Tap anywhere on card/backdrop to dismiss
    backdrop.on('pointerdown', dismiss);
    const dismiss = () => {
      backdrop.destroy();
      cardBg.destroy();
      // destroy all text objects we added (use depth tag via getAllChildren is harder, so just schedule cleanup)
      this.time.delayedCall(50, onDone);
    };
    backdrop.on('pointerdown', dismiss);
  }

  // ==========================================================================
  // LEVEL UP
  // ==========================================================================

  _onLevelUp(unit) {
    this._levelUps.push({ name: unit.name, emoji: unit.emoji, newLevel: unit.level });
    AudioManager.play(this, 'level_up');
    this._floatText(unit.col, unit.row, `Level Up! Lv${unit.level}`, PAL.GOLD);
    // Golden flash
    this.tweens.add({
      targets: unit.spriteBg,
      fillColor: { from: 0xf8d030, to: unit.team === 'player' ? 0x224488 : 0x882222 },
      duration: 600,
    });

    if (unit.canPromote()) {
      this._floatText(unit.col, unit.row, 'Can Promote!', 0xff88ff);
    }
  }

  // ==========================================================================
  // DIALOGUE SYSTEM
  // ==========================================================================

  _startDialogue(lines, onDone) {
    this._dlgQueue  = lines;
    this._dlgIndex  = 0;
    this._dlgOnDone = onDone;
    this._setState(BS.DIALOGUE);
    this._showDialogueLine(this._dlgQueue[0]);
    this._getUI()?.showDialogue(this._dlgQueue[0]);
  }

  _showDialogueLine(line) {
    this._getUI()?.showDialogue(line);
  }

  _advanceDialogue() {
    this._dlgIndex++;
    if (this._dlgIndex >= this._dlgQueue.length) {
      this._getUI()?.hideDialogue();
      if (this._dlgOnDone) this._dlgOnDone();
      return;
    }
    this._showDialogueLine(this._dlgQueue[this._dlgIndex]);
  }

  // ==========================================================================
  // VISUAL EFFECTS
  // ==========================================================================

  _floatText(col, row, text, color, size = 17) {
    const { x, y } = this._tileCenter(col, row);
    const t = this.add.text(x, y, text, {
      fontSize: `${size}px`,
      color: '#' + color.toString(16).padStart(6, '0'),
      stroke: '#000000',
      strokeThickness: size > 20 ? 5 : 4,
      fontFamily: 'Nunito, Courier New, monospace',
      fontStyle: 'bold',
    }).setOrigin(0.5).setDepth(20);
    this.tweens.add({
      targets: t,
      y: y - (size > 20 ? 60 : 44),
      alpha: 0,
      scaleX: size > 20 ? 1.4 : 1,
      scaleY: size > 20 ? 1.4 : 1,
      duration: size > 20 ? 900 : 1200,
      ease: 'Power1',
      onComplete: () => t.destroy(),
    });
  }

  // "★ CRITICAL! ★" screen flash + banner — called in parallel with damage float
  _floatCritBanner(col, row) {
    // Quick white flash over the whole scene
    const flash = this.add.rectangle(GAME_W / 2, GAME_H / 2, GAME_W, GAME_H, 0xffffff, 0.55)
      .setDepth(30);
    this.tweens.add({ targets: flash, alpha: 0, duration: 200, onComplete: () => flash.destroy() });

    // Screen shake via camera
    this.cameras.main.shake(180, 0.014);

    // Large "★ CRITICAL! ★" text rising from the tile
    const { x, y } = this._tileCenter(col, row);
    const banner = this.add.text(x, y - 10, '★ CRITICAL! ★', {
      fontSize: '22px',
      color: '#ffd700',
      stroke: '#000000',
      strokeThickness: 6,
      fontFamily: 'Nunito, Courier New, monospace',
      fontStyle: 'bold',
    }).setOrigin(0.5).setDepth(25);
    this.tweens.add({
      targets: banner,
      y: y - 70,
      alpha: 0,
      duration: 1100,
      ease: 'Power2',
      onComplete: () => banner.destroy(),
    });
  }

  _shakeSprite(sprite, onDone) {
    if (!sprite) { onDone && onDone(); return; }
    const origX = sprite.x;
    this.tweens.add({
      targets: sprite,
      x: { from: origX - 4, to: origX + 4 },
      duration: 50, yoyo: true, repeat: 3,
      onComplete: () => { sprite.setX(origX); onDone && onDone(); },
    });
  }

  // Show terrain name + DEF bonus briefly when a unit lands on a defensive tile
  _showTerrainLanding(unit) {
    const tid  = this.mapGrid[unit.row][unit.col];
    const terr = TERRAIN[tid];
    if (!terr || terr.def <= 0) return; // only show on tiles with a defense bonus

    const defIcons = ['', '🛡', '🛡🛡', '🛡🛡🛡'];
    const icon  = defIcons[Math.min(terr.def, 3)];
    const label = `${terr.name}  ${icon} +${terr.def} DEF`;

    const W = GAME_W;
    const bannerY = GRID_Y + this.mapGrid.length * TILE - 22; // just above the UI panel
    const bg = this.add.graphics().setDepth(18);
    bg.fillStyle(0x000000, 0.72);
    bg.fillRoundedRect(GRID_X + 4, bannerY - 14, GW - 8, 24, 6);

    const txt = this.add.text(W / 2, bannerY - 2, label, {
      fontSize: '14px',
      color: '#88ddff',
      stroke: '#000000',
      strokeThickness: 3,
      fontFamily: 'Nunito, Courier New, monospace',
      fontStyle: 'bold',
    }).setOrigin(0.5).setDepth(19);

    this.tweens.add({
      targets: [bg, txt],
      alpha: 0,
      duration: 500,
      delay: 1200,
      onComplete: () => { bg.destroy(); txt.destroy(); },
    });
  }

  // ==========================================================================
  // BOSS INTRODUCTION
  // ==========================================================================

  _showBossIntro(bossUnit, onDone) {
    this._setState(BS.ANIMATING);
    const W = GAME_W, H = GAME_H;

    // Darken the scene
    const shade = this.add.rectangle(W/2, H/2, W, H, 0x000000, 0).setDepth(40);
    this.tweens.add({ targets: shade, alpha: 0.6, duration: 400 });

    // Red glow pulse on the boss sprite
    if (bossUnit.spriteBg) {
      this.tweens.add({
        targets: bossUnit.spriteBg,
        fillColor: { from: 0x882222, to: 0xff2200 },
        duration: 300, yoyo: true, repeat: 3,
      });
    }

    // Boss frame — slides in from top
    const frameH = 90, frameY = H / 2 - 45;
    const frameBg = this.add.graphics().setDepth(42);
    frameBg.fillStyle(0x1a0000, 0.95);
    frameBg.fillRect(0, frameY, W, frameH);
    frameBg.lineStyle(2, 0xff2200, 0.9);
    frameBg.lineBetween(0, frameY, W, frameY);
    frameBg.lineBetween(0, frameY + frameH, W, frameY + frameH);
    frameBg.setY(-frameH);
    this.tweens.add({ targets: frameBg, y: 0, duration: 350, ease: 'Back.easeOut' });

    // Boss emoji (large)
    const bossEmoji = this.add.text(W / 2, frameY + frameH / 2 - 18, bossUnit.emoji, {
      fontSize: '48px',
    }).setOrigin(0.5).setDepth(43).setAlpha(0);

    // Boss name
    const bossLabel = this.add.text(W / 2, frameY + frameH / 2 + 20, bossUnit.name.toUpperCase(), {
      fontSize: '20px', color: '#ff4444',
      stroke: '#000000', strokeThickness: 5,
      fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
    }).setOrigin(0.5).setDepth(43).setAlpha(0);

    const bossClass = this.add.text(W / 2, frameY + frameH / 2 + 44,
      `${bossUnit.unitClass}  ·  LV ${bossUnit.level}`, {
        fontSize: '13px', color: '#ff9999',
        stroke: '#000000', strokeThickness: 3,
        fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
    }).setOrigin(0.5).setDepth(43).setAlpha(0);

    const tagline = this.add.text(W / 2, frameY + 8, '— ENEMY COMMANDER —', {
      fontSize: '11px', color: '#ff6666',
      stroke: '#000000', strokeThickness: 2,
      fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
    }).setOrigin(0.5, 0).setDepth(43).setAlpha(0);

    // Staggered fade-in
    this.time.delayedCall(300, () => {
      this.tweens.add({ targets: [bossEmoji, tagline], alpha: 1, duration: 250 });
      this.time.delayedCall(150, () => {
        this.tweens.add({ targets: bossLabel, alpha: 1, duration: 250,
          onComplete: () => this.tweens.add({ targets: bossClass, alpha: 1, duration: 200 }) });
      });
    });

    // Dismiss on tap or after 2.5s
    const allObjs = [shade, frameBg, bossEmoji, bossLabel, bossClass, tagline];
    const dismiss = () => {
      tapZone.removeAllListeners();
      this.tweens.add({
        targets: allObjs, alpha: 0, duration: 400,
        onComplete: () => { allObjs.forEach(o => o.destroy()); tapZone.destroy(); onDone && onDone(); },
      });
    };
    const tapZone = this.add.zone(W/2, H/2, W, H).setInteractive().setDepth(44);
    tapZone.on('pointerdown', dismiss);
    this.time.delayedCall(2500, () => { if (tapZone.active) dismiss(); });
  }

  _healEffect(col, row) {
    const { x, y } = this._tileCenter(col, row);
    for (let i = 0; i < 6; i++) {
      const dot = this.add.circle(
        x + Phaser.Math.Between(-12, 12),
        y + Phaser.Math.Between(-12, 12),
        Phaser.Math.Between(2, 5), 0x44ff88, 0.9
      );
      this.tweens.add({
        targets: dot, y: dot.y - 20, alpha: 0, scaleX: 2, scaleY: 2,
        duration: 500, delay: i * 60,
        onComplete: () => dot.destroy(),
      });
    }
  }

  // Grey out units that have acted; stop/start idle bobs accordingly
  _dimActedUnits() {
    this.units.forEach(u => {
      if (!u.sprite) return;
      const dim = (u.team === 'player') && (u.hasMoved && u.hasActed);
      const alpha = dim ? 0.45 : 1.0;
      u.sprite.setAlpha(alpha);
      u.spriteBg?.setAlpha(alpha);
      u.badge?.setAlpha(alpha);
      // Stop bob for acted units, restart for ready ones
      if (u.team === 'player') {
        if (dim) {
          this._stopIdleBob(u);
        } else if (!u._bobTween) {
          this._startIdleBob(u);
        }
      }
    });
  }

  // ==========================================================================
  // UTILITIES
  // ==========================================================================

  _setState(state) { this._state = state; }

  _unitAt(col, row) {
    return this.units.find(u => !u.dead && u.isOccupyingTile(col, row)) || null;
  }

  _tileCenter(col, row) {
    return {
      x: GRID_X + col * TILE + TILE / 2,
      y: GRID_Y + row * TILE + TILE / 2,
    };
  }

  _unitCenter(unit) {
    const sz = unit.tileSize || 1;
    return {
      x: GRID_X + unit.col * TILE + (sz * TILE) / 2,
      y: GRID_Y + unit.row * TILE + (sz * TILE) / 2,
    };
  }

  _tileTL(col, row) {
    return { x: GRID_X + col * TILE, y: GRID_Y + row * TILE };
  }

  _getUI() {
    return this.scene.isActive('UIScene') ? this.scene.get('UIScene') : null;
  }

  _showUnitInfo(unit) {
    this._getUI()?.showUnitInfo(unit);
  }

  // ==========================================================================
  // m5: AUTO-END TURN
  // ==========================================================================

  _checkAutoEndTurn() {
    if (this._battleEnded) return;
    if (this._autoEndTimer) return;  // already scheduled — prevent double-schedule
    const state = this._getState();
    if (state === BS.ENEMY_TURN || state === BS.ANIMATING || state === BS.VICTORY || state === BS.DEFEAT) return;
    const livingPlayers = this.units.filter(u => !u.dead && u.team === 'player');
    if (livingPlayers.length > 0 && livingPlayers.every(u => u.hasMoved && u.hasActed)) {
      this._autoEndTimer = this.time.delayedCall(400, () => {
        this._autoEndTimer = null;
        if (!this._battleEnded) this.onEndTurn();
      });
    }
  }

  _getState() { return this._state; }

  // ==========================================================================
  // C2: WEAPON EFFECTIVENESS
  // ==========================================================================

  _weaponEffectiveness(attacker, defender) {
    const ac = attacker.unitClass || '';
    const dc = defender.unitClass || '';
    // Bows effective vs Cavalry
    if ((ac === 'Archer' || ac === 'Ranger') && (dc === 'Cavalry' || dc === 'Champion')) return 1.5;
    // Cavalry effective vs foot soldiers (Knight, Warrior, Baron)
    if ((ac === 'Cavalry' || ac === 'Champion') && (dc === 'Knight' || dc === 'Warrior' || dc === 'Baron')) return 1.25;
    // Magic effective vs heavily armored (Tank/Baron/Knight)
    if ((ac === 'Mage' || ac === 'Wizard') && (dc === 'Knight' || dc === 'Baron' || dc === 'Tank')) return 1.25;
    return 1.0;
  }

  // ==========================================================================
  // M1: ENEMY RANGE PREVIEW
  // ==========================================================================

  _showEnemyRange(enemy) {
    // Clear any existing enemy range highlights
    this._clearEnemyRange();

    this._enemyRangeGfx = this.add.graphics().setDepth(1);
    const g = this._enemyRangeGfx;

    // Compute all tiles the enemy could move to
    const moveTiles = getReachableTiles(enemy, this.mapGrid, this.units);
    const highlighted = new Set();

    // For each reachable tile, compute attack tiles from that position
    moveTiles.forEach(mt => {
      const atkTiles = getAttackTiles({ ...enemy, col: mt.col, row: mt.row }, this.mapGrid, mt.col, mt.row);
      atkTiles.forEach(at => {
        const key = `${at.col},${at.row}`;
        if (!highlighted.has(key)) {
          highlighted.add(key);
          const { x, y } = this._tileTL(at.col, at.row);
          g.fillStyle(0xff4444, 0.35);
          g.fillRect(x + 2, y + 2, TILE - 4, TILE - 4);
          g.lineStyle(1, 0xff6666, 0.7);
          g.strokeRect(x + 2, y + 2, TILE - 4, TILE - 4);
        }
      });
    });
    // Also highlight the enemy's current position
    const { x: ex, y: ey } = this._tileTL(enemy.col, enemy.row);
    g.fillStyle(0xff2222, 0.25);
    g.fillRect(ex + 2, ey + 2, TILE - 4, TILE - 4);
    g.lineStyle(2, 0xff2222, 0.9);
    g.strokeRect(ex + 2, ey + 2, TILE - 4, TILE - 4);
  }

  _clearEnemyRange() {
    if (this._enemyRangeGfx) {
      this._enemyRangeGfx.destroy();
      this._enemyRangeGfx = null;
    }
  }
}
