'use strict';
// =============================================================================
// Puppy Force — ComicScene.js
// Manga/anime-style inter-chapter cutscene using chibi portrait assets.
//
// Layout (top→bottom, all panels visible at once, appear sequentially):
//   Panel A — full-width  (victory line 1)
//   Panel B — left half   (victory line 2)
//   Panel C — right half  (villain reveal)
//   Panel D — full-width  (chapter title card)
// =============================================================================

class ComicScene extends Phaser.Scene {
  constructor() { super({ key: 'ComicScene' }); }

  init(data) {
    this.nextChapter = data.chapter;
    this.currentChap = data.currentChap;
    this.saveData    = data.saveData;
    this._done       = false;
  }

  // ---------------------------------------------------------------------------
  preload() {
    AudioManager.preloadMusic(this);

    const ENEMY_IDS = [
      'ALLEY_CAT', 'SIAMESE_ASSASSIN', 'LYNX_RANGER', 'SNOW_LEOPARD',
      'RIVER_PANTHER', 'SAND_CAT_KING', 'PERSIAN_QUEEN', 'CAT_EMPEROR',
      'TIGER_GENERAL', 'PERSIAN_SORCERER', 'SCOUT_CAT',
    ];
    ENEMY_IDS.forEach(id => {
      const key = `enemy_png_${id}`;
      if (!this.textures.exists(key))
        try { this.load.image(key, `assets/enemies/${id.toLowerCase()}_v1.png`); } catch (_) {}
    });

    const PLAYER_IDS = [
      'PUPPY_KNIGHT', 'CORGI_HEALER', 'LABRADOR_SCOUT', 'BEAGLE_ARCHER',
      'BULLDOG_TANK', 'POODLE_MAGE', 'HUSKY_RIDER', 'TERRIER_THIEF',
      'FOX_SCOUT', 'DOG_PALADIN', 'OTTER_ALLY',
    ];
    PLAYER_IDS.forEach(id => {
      const key = `player_png_${id}`;
      if (!this.textures.exists(key))
        try { this.load.image(key, `assets/characters/${id.toLowerCase()}_chibi_v1.png`); } catch (_) {}
    });

    // Manga panel background images (generated by scripts/generate-panels.js)
    // assets/panels/ch<N>_<slot>_v1.png — used as atmospheric BGs behind chibi portraits
    for (let ch = 1; ch <= 7; ch++) {
      ['hero', 'ally', 'villain'].forEach(slot => {
        const key = `panel_bg_${ch}_${slot}`;
        if (!this.textures.exists(key))
          try { this.load.image(key, `assets/panels/ch${ch}_${slot}_v1.png`); } catch (_) {}
      });
    }
  }

  // ---------------------------------------------------------------------------
  create() {
    const W = GAME_W, H = GAME_H;
    AudioManager.playMusic(this, 'overworld', 0.4);

    // Manga parchment background (fills gutters between panels)
    this.add.rectangle(W / 2, H / 2, W, H, 0xd8ceb8).setDepth(0);

    const beats  = this._collectBeats();
    const panels = this._computeLayout(beats, W, H);

    this._buildSkipButton(W);

    // Stagger each panel's reveal: 0 / 1700 / 3000 / 4100 ms
    const STAGGER = [0, 1700, 3000, 4100];
    panels.forEach((panel, i) => {
      this._renderPanel(panel, STAGGER[i] ?? (i * 1300));
    });

    // Auto-advance 2.8 s after the last panel appears
    const lastDelay = STAGGER[panels.length - 1] ?? ((panels.length - 1) * 1300);
    this.time.delayedCall(lastDelay + 2800, () => this._advance());
  }

  // ---------------------------------------------------------------------------
  // Build up to 3 content beats + 1 title card from chapter data
  _collectBeats() {
    const cur  = CHAPTERS[(this.currentChap || 1) - 1] || {};
    const next = CHAPTERS[(this.nextChapter  || 2) - 1] || {};
    const vict = (cur.victory  || []).slice(0, 2);
    const intr =  next.intro   || [];

    const beats = [];
    const curChap  = this.currentChap || 1;
    const nextChap = this.nextChapter  || 2;

    // Victory lines (heroes reflecting on the win)
    vict.forEach((line, i) => {
      beats.push({
        speaker:  line.speaker,
        text:     line.text,
        portrait: line.portrait || '🐶',
        key:      SPEAKER_PORTRAIT_KEY[line.speaker] || null,
        villain:  false,
        bgKey:    `panel_bg_${curChap}_${i === 0 ? 'hero' : 'ally'}`,
      });
    });

    // One villain/boss line from the next chapter's intro
    const VILLAIN_WORDS = [
      'Cat', 'Emperor', 'Queen', 'General', 'Assassin',
      'Panther', 'Leopard', 'Lynx', 'Sorcerer', 'Ranger',
    ];
    const villainLine = intr.find(
      l => VILLAIN_WORDS.some(w => (l.speaker || '').includes(w))
    );
    if (villainLine) {
      beats.push({
        speaker:  villainLine.speaker,
        text:     villainLine.text,
        portrait: villainLine.portrait || '😾',
        key:      SPEAKER_PORTRAIT_KEY[villainLine.speaker] || null,
        villain:  true,
        bgKey:    `panel_bg_${nextChap}_villain`,
      });
    }

    // Chapter title card always last
    beats.push({ type: 'title', chapterNum: this.nextChapter, title: next.title });
    return beats;
  }

  // ---------------------------------------------------------------------------
  // Map beats → panel rects.
  // Up to 3 content panels + 1 title; 3-panel layout uses full + two halves.
  _computeLayout(beats, W, H) {
    const SKIP_H = 30;
    const GAP    = 5;
    const totalH = H - SKIP_H;

    const content = beats.filter(b => !b.type);
    const title   = beats.find(b => b.type === 'title');
    const panels  = [];

    if (content.length === 0) {
      if (title) panels.push({ ...title, x: 0, y: SKIP_H, w: W, h: totalH });

    } else if (content.length === 1) {
      const h1 = Math.floor(totalH * 0.42);
      const h2 = totalH - h1 - GAP;
      panels.push({ ...content[0], x: 0, y: SKIP_H,               w: W, h: h1 });
      if (title) panels.push({ ...title, x: 0, y: SKIP_H+h1+GAP,  w: W, h: h2 });

    } else if (content.length === 2) {
      const h1 = Math.floor(totalH * 0.37);
      const h2 = Math.floor(totalH * 0.37);
      const h3 = totalH - h1 - h2 - GAP * 2;
      panels.push({ ...content[0], x: 0, y: SKIP_H,                    w: W, h: h1 });
      panels.push({ ...content[1], x: 0, y: SKIP_H+h1+GAP,             w: W, h: h2 });
      if (title) panels.push({ ...title, x: 0, y: SKIP_H+h1+h2+GAP*2, w: W, h: h3 });

    } else {
      // 3 content panels: full-top + side-by-side pair + title
      const h1 = Math.floor(totalH * 0.295);
      const h2 = Math.floor(totalH * 0.345);
      const h3 = totalH - h1 - h2 - GAP * 2;
      const hw  = Math.floor((W - GAP) / 2);

      panels.push({ ...content[0], x: 0,       y: SKIP_H,            w: W,         h: h1 });
      panels.push({ ...content[1], x: 0,       y: SKIP_H+h1+GAP,     w: hw,        h: h2 });
      panels.push({ ...content[2], x: hw+GAP,  y: SKIP_H+h1+GAP,     w: W-hw-GAP, h: h2 });
      if (title) panels.push({ ...title, x: 0, y: SKIP_H+h1+h2+GAP*2, w: W,        h: h3 });
    }

    return panels;
  }

  // ---------------------------------------------------------------------------
  // Render one panel (hidden), then animate it into view after `delay` ms.
  _renderPanel(panel, delay) {
    const container = this.add.container(panel.x, panel.y).setAlpha(0).setDepth(5);
    container.setScale(0.88);

    if (panel.type === 'title') {
      this._buildTitlePanel(container, panel.w, panel.h, panel.chapterNum, panel.title);
    } else {
      this._buildDialoguePanel(container, panel);
    }

    this.time.delayedCall(delay, () => {
      this.tweens.add({ targets: container, alpha: 1, scale: 1, duration: 380, ease: 'Back.out' });
    });
  }

  // ---------------------------------------------------------------------------
  _buildDialoguePanel(container, panel) {
    const W = panel.w, H = panel.h;
    const isVillain  = !!panel.villain;
    const isFullWide = W > 280;

    // Background: manga panel image if generated, otherwise gradient fallback
    const hasPanelBg = panel.bgKey && this.textures.exists(panel.bgKey);
    if (hasPanelBg) {
      container.add(
        this.add.image(W / 2, H / 2, panel.bgKey).setDisplaySize(W, H).setOrigin(0.5)
      );
      // Semi-transparent tint overlay for atmosphere + readability
      const overlay = this.add.graphics();
      overlay.fillStyle(isVillain ? 0x220000 : 0xddf5cc, isVillain ? 0.50 : 0.30);
      overlay.fillRect(0, 0, W, H);
      container.add(overlay);
    } else {
      // Gradient fallback (used until panel images are generated)
      const bg = this.add.graphics();
      if (isVillain) {
        bg.fillGradientStyle(0x220a0a, 0x3a0d0d, 0x3a0d0d, 0x220a0a, 1);
      } else {
        bg.fillGradientStyle(0xc4d8a8, 0xd8ecc0, 0xd8ecc0, 0xc4d8a8, 1);
      }
      bg.fillRect(0, 0, W, H);
      container.add(bg);
    }

    // Villain: radiating speed lines behind portrait
    if (isVillain) this._addSpeedLines(container, W, H);

    // Portrait position — hero faces right (default), villain faces left (flipped)
    const maxPortrait = Math.min(W / 2.4, H * 0.88);
    const portraitSz  = Math.round(maxPortrait);
    let px, py;
    if (isFullWide) {
      px = isVillain ? W * 0.76 : W * 0.20;
      py = H * 0.56;
    } else {
      px = W * 0.50;
      py = H * 0.70;
    }

    const key = panel.key;
    let portraitObj;
    if (key && this.textures.exists(key)) {
      portraitObj = this.add.image(px, py, key)
        .setDisplaySize(portraitSz, portraitSz)
        .setOrigin(0.5)
        .setFlipX(isVillain);
    } else {
      portraitObj = this.add.text(px, py, panel.portrait, {
        fontSize: Math.floor(portraitSz * 0.62) + 'px',
      }).setOrigin(0.5);
    }
    container.add(portraitObj);

    // Speech bubble
    this._addSpeechBubble(container, panel, W, H, isFullWide, isVillain);

    // Panel border (drawn last, on top)
    const border = this.add.graphics();
    border.lineStyle(3, 0x111111, 1);
    border.strokeRect(0, 0, W, H);
    if (isVillain) {
      border.lineStyle(2, 0xcc2222, 0.9);
      border.strokeRect(3, 3, W - 6, H - 6);
    }
    container.add(border);
  }

  _addSpeechBubble(container, panel, W, H, isFullWide, isVillain) {
    let bx, by, bw, bh;
    if (isFullWide) {
      bw = Math.floor(W * 0.56);
      bh = Math.floor(H * 0.72);
      bx = isVillain ? 8 : W - bw - 8;
      by = 8;
    } else {
      bx = 6; by = 6;
      bw = W - 12;
      bh = Math.floor(H * 0.44);
    }

    const g = this.add.graphics();
    g.fillStyle(0xffffff, 0.93);
    g.fillRoundedRect(bx, by, bw, bh, 9);
    g.lineStyle(2, isVillain ? 0xcc2222 : 0x222222, 1);
    g.strokeRoundedRect(bx, by, bw, bh, 9);
    container.add(g);

    // Speaker name
    const nameColor = isVillain ? '#cc2222' : '#224488';
    container.add(this.add.text(bx + 8, by + 7, panel.speaker, {
      fontSize: '11px', color: nameColor,
      fontFamily: 'Nunito, Arial, sans-serif', fontStyle: 'bold',
    }).setOrigin(0, 0));

    // Divider
    const div = this.add.graphics();
    div.lineStyle(1, 0xbbbbbb, 0.8);
    div.lineBetween(bx + 6, by + 23, bx + bw - 6, by + 23);
    container.add(div);

    // Dialogue
    container.add(this.add.text(bx + 8, by + 29, panel.text || '', {
      fontSize: '10px', color: '#111111',
      fontFamily: 'Nunito, Arial, sans-serif',
      wordWrap: { width: bw - 16 }, lineSpacing: 3,
    }).setOrigin(0, 0));
  }

  // Radiating speed lines contained within the panel bounds
  _addSpeedLines(container, W, H) {
    const g  = this.add.graphics();
    g.lineStyle(1, 0xaa1111, 0.20);
    const cx = W / 2, cy = H / 2;
    // Outer radius capped so lines don't exceed the shorter panel dimension
    const outer = Math.min(W, H) / 2 * 0.96;
    const inner = Math.min(W, H) / 2 * 0.22;
    for (let a = 0; a < 360; a += 10) {
      const rad = (a * Math.PI) / 180;
      g.lineBetween(
        cx + Math.cos(rad) * inner, cy + Math.sin(rad) * inner,
        cx + Math.cos(rad) * outer, cy + Math.sin(rad) * outer,
      );
    }
    container.add(g);
  }

  // ---------------------------------------------------------------------------
  _buildTitlePanel(container, W, H, chapterNum, title) {
    const bg = this.add.graphics();
    bg.fillStyle(0x080c18, 1);
    bg.fillRect(0, 0, W, H);
    container.add(bg);

    // Decorative horizontal rules flanking the text
    const deco = this.add.graphics();
    deco.lineStyle(1, 0x334466, 0.55);
    deco.lineBetween(30, H / 2 - 26, W - 30, H / 2 - 26);
    deco.lineBetween(30, H / 2 + 52, W - 30, H / 2 + 52);
    container.add(deco);

    container.add(this.add.text(W / 2, H / 2 - 32, `CHAPTER ${chapterNum}`, {
      fontSize: '12px', color: '#aabbcc', letterSpacing: 6,
      fontFamily: 'Nunito, Arial, sans-serif', fontStyle: 'bold',
      stroke: '#000000', strokeThickness: 2,
    }).setOrigin(0.5));

    container.add(this.add.text(W / 2, H / 2 + 10, title || '', {
      fontSize: '28px', color: '#f8d030',
      fontFamily: 'Nunito, Georgia, serif', fontStyle: 'bold',
      stroke: '#000000', strokeThickness: 4,
    }).setOrigin(0.5));

    const border = this.add.graphics();
    border.lineStyle(3, 0x111111, 1);
    border.strokeRect(0, 0, W, H);
    container.add(border);
  }

  // ---------------------------------------------------------------------------
  _buildSkipButton(W) {
    const btn = this.add.text(W - 14, 14, 'SKIP ▶▶', {
      fontSize: '12px', color: '#778899',
      fontFamily: 'Nunito, Arial, sans-serif', fontStyle: 'bold',
      backgroundColor: '#00000088',
      padding: { x: 6, y: 3 },
    }).setOrigin(1, 0).setDepth(20).setInteractive({ useHandCursor: true });

    btn.on('pointerover', () => btn.setColor('#aabbff'));
    btn.on('pointerout',  () => btn.setColor('#778899'));
    btn.on('pointerdown', () => this._advance());
  }

  // ---------------------------------------------------------------------------
  _advance() {
    if (this._done) return;
    this._done = true;
    const W = GAME_W, H = GAME_H;
    const overlay = this.add.rectangle(W / 2, H / 2, W, H, 0x000000, 0).setDepth(50);
    this.tweens.add({
      targets: overlay, alpha: 1, duration: 600,
      onComplete: () => {
        this.scene.start('PrepScene', { chapter: this.nextChapter, saveData: this.saveData });
      },
    });
  }
}
