'use strict';
// =============================================================================
// Puppy Force — InnScene.js
// Character gallery — review and compare Dark Fantasy vs Chibi sprite styles.
// SVG sprites always show as fallback; PixelLab PNGs auto-load when present.
//
// Texture key conventions:
//   inn_dark_<ID>  — PixelLab dark-fantasy sprite variant
//   inn_chibi_<ID> — PixelLab chibi sprite variant
//   spr_<...>      — SVG fallback (generated by SpriteSheet.js)
// =============================================================================

class InnScene extends Phaser.Scene {

  constructor() {
    super({ key: 'InnScene' });
  }

  // ---------------------------------------------------------------------------
  preload() {
    // Ensure SVG sprites are available even if BattleScene hasn't run yet
    preloadUnitSprites(this);

    // Suppress load errors for optional PixelLab PNGs
    this.load.on('loaderror', () => {});

    Object.keys(ENEMY_DEFS).forEach(id => {
      const lc = id.toLowerCase();
      this.load.image(`inn_dark_${id}`,  `assets/enemies/${lc}_pl_v1.png`);
      this.load.image(`inn_chibi_${id}`, `assets/enemies/${lc}_chibi_v1.png`);
    });
    Object.keys(HERO_DEFS).forEach(id => {
      const lc = id.toLowerCase();
      this.load.image(`inn_dark_${id}`,  `assets/characters/${lc}_sprite_v1.png`);
      this.load.image(`inn_chibi_${id}`, `assets/characters/${lc}_chibi_v1.png`);
    });
  }

  // ---------------------------------------------------------------------------
  create() {
    const W = this.scale.width;
    const H = this.scale.height;

    this._filter    = 'all';   // 'all' | 'heroes' | 'enemies'
    this._style     = 'dark';  // 'dark' | 'chibi'
    this._scrollY   = 0;
    this._maxScroll = 0;
    this._dragging  = false;
    this._dragBase  = 0;

    // ── Background ────────────────────────────────────────────────────────────
    this.add.rectangle(W/2, H/2, W, H, 0x0b0a08);
    // Subtle warm grain
    for (let i = 0; i < 60; i++) {
      this.add.rectangle(
        Phaser.Math.Between(0, W), Phaser.Math.Between(0, H),
        1, 1, 0x3a2a10,
        Phaser.Math.FloatBetween(0.1, 0.5)
      );
    }

    // ── Header ────────────────────────────────────────────────────────────────
    // Warm header bar
    this.add.rectangle(W/2, 36, W, 72, 0x150f08);
    this.add.rectangle(W/2, 72, W, 2, 0xc8820a, 0.6);

    // Back button
    const backLabel = this.add.text(14, 20, '◀ BACK', {
      fontSize: '13px', color: '#887755',
      fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
    }).setInteractive({ useHandCursor: true }).setOrigin(0, 0);
    backLabel.on('pointerover', () => backLabel.setColor('#f8d030'));
    backLabel.on('pointerout',  () => backLabel.setColor('#887755'));
    backLabel.on('pointerdown', () => this.scene.start('TitleScene'));

    // Title
    this.add.text(W/2, 12, 'THE INN', {
      fontSize: '26px', color: '#f8d030',
      fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
      stroke: '#3a1a00', strokeThickness: 4,
    }).setOrigin(0.5, 0);

    this.add.text(W/2, 42, 'CHARACTER GALLERY  —  PUPPY FORCE', {
      fontSize: '10px', color: '#6a5030',
      fontFamily: 'Courier New, monospace', letterSpacing: 1,
    }).setOrigin(0.5, 0);

    // Counter (shows how many sprites have been generated)
    const darkCount  = this._countLoaded('dark');
    const chibiCount = this._countLoaded('chibi');
    this.add.text(W/2, 56, `⚡ ${darkCount} dark  ✨ ${chibiCount} chibi  sprites generated`, {
      fontSize: '10px', color: '#4a3820',
      fontFamily: 'Courier New, monospace',
    }).setOrigin(0.5, 0);

    // ── Filter tabs ───────────────────────────────────────────────────────────
    this._filterBtns = {};
    const TABS = [
      { key: 'all',     label: 'ALL'      },
      { key: 'heroes',  label: '⚔ HEROES' },
      { key: 'enemies', label: '🐱 ENEMIES' },
    ];
    const TAB_W = 136, TAB_H = 28, TAB_Y = 88, TAB_GAP = 4;
    const tabRowW = TABS.length * TAB_W + (TABS.length - 1) * TAB_GAP;
    let tabX = W/2 - tabRowW/2 + TAB_W/2;

    TABS.forEach(tab => {
      const gfx  = this.add.graphics();
      const txt  = this.add.text(tabX, TAB_Y, tab.label, {
        fontSize: '13px', color: '#ccaa66',
        fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
      }).setOrigin(0.5);
      const zone = this.add.zone(tabX, TAB_Y, TAB_W, TAB_H).setInteractive({ useHandCursor: true });
      this._filterBtns[tab.key] = { gfx, txt, zone, x: tabX, y: TAB_Y, w: TAB_W, h: TAB_H };

      zone.on('pointerover', () => {
        if (this._filter !== tab.key) { gfx.clear(); this._strokeTab(gfx, tabX, TAB_Y, TAB_W, TAB_H, 0xc8820a, 0.5); }
      });
      zone.on('pointerout', () => {
        if (this._filter !== tab.key) this._drawTab(tab.key, false);
      });
      zone.on('pointerdown', () => {
        if (this._filter === tab.key) return;
        this._filter = tab.key;
        this._scrollY = 0;
        this._refreshAllTabs();
        this._rebuildGrid();
      });
      tabX += TAB_W + TAB_GAP;
    });

    // ── Style toggle ──────────────────────────────────────────────────────────
    this._styleBtns = {};
    const STYLES = [
      { key: 'dark',  label: '⚡ DARK',  color: 0xff6644 },
      { key: 'chibi', label: '✨ CHIBI', color: 0xff88cc },
    ];
    const ST_W = 96, ST_H = 24, ST_Y = 118, ST_GAP = 6;
    const stRowW = STYLES.length * ST_W + (STYLES.length - 1) * ST_GAP;

    this.add.text(W/2 - stRowW/2 - 6, ST_Y, 'STYLE:', {
      fontSize: '10px', color: '#4a3820',
      fontFamily: 'Courier New, monospace',
    }).setOrigin(1, 0.5);

    let stX = W/2 - stRowW/2 + ST_W/2;
    STYLES.forEach(s => {
      const gfx  = this.add.graphics();
      const txt  = this.add.text(stX, ST_Y, s.label, {
        fontSize: '12px', color: '#886644',
        fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
      }).setOrigin(0.5);
      const zone = this.add.zone(stX, ST_Y, ST_W, ST_H).setInteractive({ useHandCursor: true });
      this._styleBtns[s.key] = { gfx, txt, zone, x: stX, y: ST_Y, w: ST_W, h: ST_H, color: s.color };

      zone.on('pointerdown', () => {
        if (this._style === s.key) return;
        this._style = s.key;
        this._scrollY = 0;
        this._refreshAllStyleBtns();
        this._rebuildGrid();
      });
      stX += ST_W + ST_GAP;
    });

    // ── Scrollable content area ───────────────────────────────────────────────
    const CONTENT_TOP = 134;
    const CONTENT_H   = H - CONTENT_TOP;
    this._cTop = CONTENT_TOP;
    this._cH   = CONTENT_H;

    // Scrollbar track (decorative)
    this._sbTrack = this.add.rectangle(W - 5, CONTENT_TOP + CONTENT_H/2, 3, CONTENT_H, 0x2a1a08, 0.7);
    this._sbThumb = this.add.rectangle(W - 5, CONTENT_TOP + 10, 3, 40, 0xc8820a, 0.6);

    // Scroll container
    this._grid = this.add.container(0, CONTENT_TOP);

    const maskGfx = this.add.graphics();
    maskGfx.fillRect(0, CONTENT_TOP, W, CONTENT_H);
    this._grid.setMask(new Phaser.Display.Masks.GeometryMask(this, maskGfx));

    // Initial render
    this._refreshAllTabs();
    this._refreshAllStyleBtns();
    this._rebuildGrid();
    this._setupInput();
  }

  // ---------------------------------------------------------------------------
  // ── Drawing helpers ─────────────────────────────────────────────────────────

  _strokeTab(gfx, x, y, w, h, color, alpha) {
    gfx.lineStyle(1.5, color, alpha);
    gfx.strokeRoundedRect(x - w/2, y - h/2, w, h, 4);
  }

  _drawTab(key, active) {
    const b = this._filterBtns[key];
    b.gfx.clear();
    if (active) {
      b.gfx.fillStyle(0xc8820a, 0.18);
      b.gfx.fillRoundedRect(b.x - b.w/2, b.y - b.h/2, b.w, b.h, 4);
      b.gfx.lineStyle(2, 0xf8d030, 0.9);
      b.gfx.strokeRoundedRect(b.x - b.w/2, b.y - b.h/2, b.w, b.h, 4);
      b.txt.setColor('#f8d030');
    } else {
      b.gfx.lineStyle(1.5, 0x3a2a10, 0.8);
      b.gfx.strokeRoundedRect(b.x - b.w/2, b.y - b.h/2, b.w, b.h, 4);
      b.txt.setColor('#6a5030');
    }
  }

  _refreshAllTabs() {
    Object.keys(this._filterBtns).forEach(k => this._drawTab(k, k === this._filter));
  }

  _drawStyleBtn(key, active) {
    const b = this._styleBtns[key];
    b.gfx.clear();
    if (active) {
      b.gfx.fillStyle(b.color, 0.2);
      b.gfx.fillRoundedRect(b.x - b.w/2, b.y - b.h/2, b.w, b.h, 4);
      b.gfx.lineStyle(2, b.color, 1.0);
      b.gfx.strokeRoundedRect(b.x - b.w/2, b.y - b.h/2, b.w, b.h, 4);
      b.txt.setColor(key === 'dark' ? '#ffaa88' : '#ffaaee');
    } else {
      b.gfx.lineStyle(1.5, 0x3a2a10, 0.8);
      b.gfx.strokeRoundedRect(b.x - b.w/2, b.y - b.h/2, b.w, b.h, 4);
      b.txt.setColor('#4a3420');
    }
  }

  _refreshAllStyleBtns() {
    Object.keys(this._styleBtns).forEach(k => this._drawStyleBtn(k, k === this._style));
  }

  // ---------------------------------------------------------------------------
  // ── Card grid ───────────────────────────────────────────────────────────────

  _getUnits() {
    const heroes  = Object.values(HERO_DEFS);
    const enemies = Object.values(ENEMY_DEFS);
    if (this._filter === 'heroes')  return heroes;
    if (this._filter === 'enemies') return enemies;
    return [...heroes, ...enemies];
  }

  _hasTexture(key) {
    return this.textures.exists(key) &&
           this.textures.get(key).key !== '__MISSING';
  }

  _countLoaded(style) {
    const allIds = [
      ...Object.keys(HERO_DEFS),
      ...Object.keys(ENEMY_DEFS),
    ];
    return allIds.filter(id => this._hasTexture(`inn_${style}_${id}`)).length;
  }

  _getBestSpriteKey(unitDef) {
    // Prefer PixelLab PNG for current style
    const plKey = `inn_${this._style}_${unitDef.id}`;
    if (this._hasTexture(plKey)) return { key: plKey, isPixellab: true };
    // SVG fallback
    const svgKey = getSpriteKey(unitDef);
    if (this._hasTexture(svgKey)) return { key: svgKey, isPixellab: false };
    return null;
  }

  _rebuildGrid() {
    this._grid.removeAll(true);

    const W      = this.scale.width;
    const COLS   = 3;
    const CARD_W = 146;
    const CARD_H = 188;
    const GAP_X  = 7;
    const GAP_Y  = 8;
    const MARGIN = Math.floor((W - (COLS * CARD_W + (COLS - 1) * GAP_X)) / 2);
    const PAD_T  = 10;

    const units = this._getUnits();
    units.forEach((def, idx) => {
      const col = idx % COLS;
      const row = Math.floor(idx / COLS);
      const cx  = MARGIN + col * (CARD_W + GAP_X) + CARD_W / 2;
      const cy  = PAD_T  + row * (CARD_H + GAP_Y) + CARD_H / 2;
      this._makeCard(def, cx, cy);
    });

    const rows     = Math.ceil(units.length / COLS);
    const totalH   = PAD_T + rows * CARD_H + (rows - 1) * GAP_Y + 20;
    this._maxScroll = Math.max(0, totalH - this._cH);
    this._scrollY   = Phaser.Math.Clamp(this._scrollY, 0, this._maxScroll);
    this._applyScroll();
  }

  _makeCard(def, cx, cy) {
    const CARD_W = 146;
    const CARD_H = 188;
    const isHero = def.team === 'player';
    const isBoss = !!def.isBoss;

    // Color scheme per team / boss status
    const bgColor  = isHero ? 0x080e1a : (isBoss ? 0x1a0808 : 0x0d0a12);
    const rimColor = isHero ? 0x4466aa : (isBoss ? 0xcc3310 : 0x553322);
    const rimW     = isBoss ? 2.5 : 1.5;
    const rimAlpha = isBoss ? 1.0 : 0.7;

    // ── Card background ───────────────────────────────────────────────────
    const bg = this.add.graphics();
    bg.fillStyle(bgColor, 0.97);
    bg.fillRoundedRect(cx - CARD_W/2, cy - CARD_H/2, CARD_W, CARD_H, 6);
    bg.lineStyle(rimW, rimColor, rimAlpha);
    bg.strokeRoundedRect(cx - CARD_W/2, cy - CARD_H/2, CARD_W, CARD_H, 6);
    this._grid.add(bg);

    // Inner subtle glow on bosses
    if (isBoss) {
      const glow = this.add.graphics();
      glow.lineStyle(6, rimColor, 0.08);
      glow.strokeRoundedRect(cx - CARD_W/2 + 3, cy - CARD_H/2 + 3, CARD_W - 6, CARD_H - 6, 5);
      this._grid.add(glow);
    }

    // ── Team/role badge (top-right) ───────────────────────────────────────
    const roleBadge = isBoss ? '👑' : (isHero ? '⭐' : '');
    if (roleBadge) {
      this._grid.add(
        this.add.text(cx + CARD_W/2 - 12, cy - CARD_H/2 + 12, roleBadge, {
          fontSize: '12px',
        }).setOrigin(0.5)
      );
    }

    // ── Sprite image ──────────────────────────────────────────────────────
    // Center of sprite: 16px from top + 50px = 66px from card top
    const sprY = cy - CARD_H/2 + 66;
    const texInfo = this._getBestSpriteKey(def);

    let sprObj;
    if (texInfo) {
      // Base display size — bosses slightly larger, PixelLab art larger
      const baseSize = texInfo.isPixellab ? (isBoss ? 88 : 76) : (isBoss ? 68 : 58);
      sprObj = this.add.image(cx, sprY, texInfo.key).setDisplaySize(baseSize, baseSize);
    } else {
      sprObj = this.add.text(cx, sprY, def.emoji || '❓', {
        fontSize: '40px',
      }).setOrigin(0.5);
    }
    this._grid.add(sprObj);

    // ── Style source label (below sprite) ────────────────────────────────
    const darkReady  = this._hasTexture(`inn_dark_${def.id}`);
    const chibiReady = this._hasTexture(`inn_chibi_${def.id}`);

    if (texInfo && texInfo.isPixellab) {
      // Showing a PixelLab sprite — label which style
      const styleLabel = this._style === 'dark' ? '⚡ DARK' : '✨ CHIBI';
      const sColor     = this._style === 'dark' ? '#ff8844' : '#ff88ee';
      this._grid.add(
        this.add.text(cx, cy - CARD_H/2 + 112, styleLabel, {
          fontSize: '9px', color: sColor,
          fontFamily: 'Courier New, monospace', fontStyle: 'bold',
          backgroundColor: this._style === 'dark' ? '#200800' : '#1a0014',
          padding: { x: 4, y: 2 },
        }).setOrigin(0.5, 0)
      );
    } else {
      // SVG fallback — show pending status
      this._grid.add(
        this.add.text(cx, cy - CARD_H/2 + 112, '⟳ SVG FALLBACK', {
          fontSize: '8px', color: '#3a2a14',
          fontFamily: 'Courier New, monospace',
        }).setOrigin(0.5, 0)
      );
    }

    // ── Unit name ─────────────────────────────────────────────────────────
    const nameColor = isHero ? '#88aaee' : (isBoss ? '#ffaa77' : '#bb8866');
    this._grid.add(
      this.add.text(cx, cy - CARD_H/2 + 124, def.name || def.id, {
        fontSize: '13px', color: nameColor,
        fontFamily: 'Nunito, Courier New, monospace', fontStyle: 'bold',
        stroke: '#000000', strokeThickness: 2,
        wordWrap: { width: CARD_W - 12 }, align: 'center',
      }).setOrigin(0.5, 0)
    );

    // ── Class + level ────────────────────────────────────────────────────
    const lvl = def.baseStats ? def.baseStats.level : 1;
    this._grid.add(
      this.add.text(cx, cy - CARD_H/2 + 141, `${def.unitClass}  Lv.${lvl}`, {
        fontSize: '10px', color: '#5a4a30',
        fontFamily: 'Courier New, monospace',
      }).setOrigin(0.5, 0)
    );

    // ── Mini stat bar ────────────────────────────────────────────────────
    if (def.baseStats) {
      const { maxHp: hp, atk, def: df } = def.baseStats;
      this._grid.add(
        this.add.text(cx, cy - CARD_H/2 + 154,
          `HP ${hp}  ATK ${atk}  DEF ${df}`, {
          fontSize: '9px', color: '#3a2a14',
          fontFamily: 'Courier New, monospace',
        }).setOrigin(0.5, 0)
      );
    }

    // ── Art availability indicators ──────────────────────────────────────
    const badgeY = cy + CARD_H/2 - 16;
    const badges = [];
    if (darkReady)  badges.push({ label: '⚡D', bg: '#1a0800', fg: '#ff8844' });
    if (chibiReady) badges.push({ label: '✨C', bg: '#1a0012', fg: '#ff88dd' });

    if (badges.length === 0) {
      this._grid.add(
        this.add.text(cx, badgeY, 'NO ART YET — GENERATE ↑', {
          fontSize: '8px', color: '#2a1a08',
          fontFamily: 'Courier New, monospace',
        }).setOrigin(0.5)
      );
    } else {
      const bSpacing = 34;
      const bStartX  = cx - ((badges.length - 1) * bSpacing) / 2;
      badges.forEach((b, i) => {
        this._grid.add(
          this.add.text(bStartX + i * bSpacing, badgeY, b.label, {
            fontSize: '9px', color: b.fg,
            fontFamily: 'Courier New, monospace', fontStyle: 'bold',
            backgroundColor: b.bg, padding: { x: 4, y: 2 },
          }).setOrigin(0.5)
        );
      });
    }
  }

  // ---------------------------------------------------------------------------
  // ── Scroll ────────────────────────────────────────────────────────────────

  _applyScroll() {
    this._grid.setY(this._cTop - this._scrollY);
    this._updateScrollbar();
  }

  _updateScrollbar() {
    if (this._maxScroll <= 0) {
      this._sbThumb.setAlpha(0);
      return;
    }
    this._sbThumb.setAlpha(0.6);
    const trackH  = this._cH;
    const thumbH  = Math.max(30, (this._cH / (this._cH + this._maxScroll)) * trackH);
    const thumbY  = this._cTop + ((this._scrollY / this._maxScroll) * (trackH - thumbH)) + thumbH/2;
    this._sbThumb.setSize(3, thumbH).setY(thumbY);
  }

  _setupInput() {
    // Mouse wheel
    this.input.on('wheel', (ptr, objs, dx, dy) => {
      this._scrollY = Phaser.Math.Clamp(this._scrollY + dy * 0.55, 0, this._maxScroll);
      this._applyScroll();
    });

    // Pointer drag (mobile-friendly)
    this.input.on('pointerdown', ptr => {
      if (ptr.y < this._cTop) return;
      this._dragging = true;
      this._dragBase = ptr.y + this._scrollY;
    });
    this.input.on('pointermove', ptr => {
      if (!this._dragging) return;
      this._scrollY = Phaser.Math.Clamp(this._dragBase - ptr.y, 0, this._maxScroll);
      this._applyScroll();
    });
    this.input.on('pointerup',   () => { this._dragging = false; });
    this.input.on('pointerout',  () => { this._dragging = false; });
  }
}
